In [2]:
import pandas as pd
import numpy as np

In [47]:
fu=pd.read_csv("flats_uncleaned.csv")

In [4]:
fu

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac
...,...,...,...,...,...,...,...,...,...,...,...
4520,6 BHK Apartment for Sale in Millionaires Lifes...,Carpet Area,2000 sqft,New Property,Poss. by Dec '26,5 out of 12,Unfurnished,South - East,"Check out Millionaires Lifestyle in Vesu, one ...",NaN,Call for Price
4521,"4 BHK Apartment for Sale in Savan Superia, Alt...",Super Area,3600 sqft,New Property,Poss. by Dec '25,5 out of 16,Unfurnished,South - East,Superia is a premium residential project launc...,NaN,Call for Price
4522,5 BHK Apartment for Sale in Roongta Green Vall...,Carpet Area,2250 sqft,New Property,Poss. by Dec '25,7 out of 13,Unfurnished,North - East,"When it comes to beautiful homes, nothing beat...",NaN,Call for Price
4523,"6 BHK Apartment for Sale in Cellestial Dreams,...",Carpet Area,3450 sqft,New Property,Ready to Move,7 out of 18,Unfurnished,North - West,"DRB Ravani Cellestial Dreams in Vesu, Surat is...",NaN,Call for Price
4524,4 BHK Apartment for Sale in Roongta Green Vall...,Super Area,4500 sqft,New Property,Ready to Move,3 out of 12,Unfurnished,North,Roongta Green Valley is one of the popular res...,NaN,Call for Price

In [4]:
fu.head()

,property_name,areaWithType,square_feet,transaction,status,floor,furnishing,facing,description,price_per_sqft,price
0,2 BHK Apartment for Sale in Dindoli Surat,Carpet Area,644 sqft,New Property,Poss. by Oct '24,5 out of 10,Unfurnished,West,"Luxury project with basement parking, Solar ro...","₹2,891 per sqft",₹33.8 Lac
1,2 BHK Apartment for Sale in Althan Surat,Super Area,1278 sqft,New Property,Poss. by Jan '26,6 out of 14,Unfurnished,South -West,2 And 3 BHK Luxurious Flat for Sell In New Alt...,"₹3,551 per sqft",₹45.4 Lac
2,2 BHK Apartment for Sale in Pal Gam Surat,Super Area,1173 sqft,Resale,Ready to Move,5 out of 13,Semi-Furnished,East,This affordable 2 BHK flat is situated along a...,"₹3,800 per sqft",₹44.6 Lac
3,2 BHK Apartment for Sale in Jahangirabad Surat,Carpet Area,700 sqft,New Property,Ready to Move,6 out of 14,Unfurnished,East,2 BHK Flat For sell IN Jahangirabad Prime Loca...,"₹3,966 per sqft",₹47 Lac
4,"2 BHK Apartment for Sale in Orchid Fantasia, P...",Super Area,1250 sqft,Orchid Fantasia,New Property,Unfurnished,2,2,"Multistorey Apartment for Sale in Palanpur, Su...","₹3,600 per sqft",₹45 Lac

In [6]:
fu['price']

0           ₹33.8 Lac
1           ₹45.4 Lac
2           ₹44.6 Lac
3             ₹47 Lac
4             ₹45 Lac
             ...
4520    Call for Price
4521    Call for Price
4522    Call for Price
4523    Call for Price
4524    Call for Price
Name: price, Length: 4525, dtype: object

In [ ]:
fu['price']=fu['price'].str.strip('ll')

#fu['price'].dropna(inplace=True)

In [24]:
fu['price'].unique()
fu['price'].dtype

dtype('O')

In [ ]:
#change the datatype of price to integer

out=[]
for i in range(len(fu['price'])):  
    try:
        out.append(int(fu['price'][i]))
    except:
        out.append(0)

In [89]:
fu['price']=out

In [91]:
fu['price']=fu['price'].astype(int)

In [92]:
fu['price'].dtype

dtype('int64')

In [44]:
fu['price'].unique()

array(['33.8', '45.4', '44.6', '47', '45', '43.2', '42.1', '44.1', '44.3',
       '40', '44', '12.5', '50', '35.8', '26.5', '42', '43', '20', '37',
       '29', '38', '13', '46.5', '41.6', '33.5', '42.5', '48', '32', '35',
       '46.2', '38.5', '23', '24', '28', '35.7', '36.5', '36', '43.6',
       '25', '41', '28.5', '9', '30', '39.5', '21.5', '10.5', '18', '10',
       '23.5', '16.3', '13.5', '49', '21', '39', '16', '27', '15', '39.9',
       '7.5', '12.8', '9.5', '31.5', '46', '6', '34', '22', '19', '8.5',
       '11', '16.5', '17', '14', '33', '20.5', '21.7', '27.5', '12', '26',
       '7.7', '44.8', '34.9', '19.5', '18.5', '48.5', '49.9', '26.7',
       '18.2', '24.5', '46.1', '14.2', '47.5', '9.3', '5', '8.9', '14.5',
       '37.6', '25.5', '29.5', '1.5', '26.8', '31', '22.5', '24.9',
       '40.4', '15.3', '7', '32.5', '1', '43.8', '14.4', '10.3', '40.5',
       '34.8', '39.8', '25.8', '3.5', '21.3', '8', '38.1', '15.5', '25.1',
       '37.9', '29.1', '1.3', '18.4', '14.1', '29.9', '45.2', '37.5',
       '32.7', '17.5', '48.8', '23.2', '4.5', '25.2', '27.2', '', '39.7',
       '43.7', '49.5', '2', '46.9', '19.8', '26.9', '21.6', '33.9',
       '34.7', '44.5', '41.3', '48.6', '45.5', '49.3', '43.1', '46.4',
       '42.2', '34.5', '28.2', '42.8', '45.3', '34.4', '30.5', '44.2',
       '48.2', '49.7', '47.8', '34.6', '49.1', '35.3', '45.1', '41.5',
       '26.4', '37.2', '46.3', '30.4', '47.1', '41.7', '33.4', '40.7',
       '36.8', '42.7', '30.6', '43.4', '38.7', '33.2', '34.3', '39.2',
       '43.9', '35.2', '31.6', '41.1', '44.9', '25.9', '42.3', '25.3',
       '36.1', '25.7', '45.6', '35.1', '36.4', '42.4', '46.7', '20.1',
       '34.1', '16.4', '43.5', '19.9', '38.2', '35.5', '67.7', '55.6',
       '98', '62.2', '69.4', '70', '56.5', '57.4', '92.9', '57.1', '55.7',
       '79.1', '65.2', '80.5', '90', '75', '52', '75.4', '74.5', '69.3',
       '60', '67.5', '51.5', '67.4', '55', '50.3', '66.3', '80', '50.6',
       '61', '51', '50.8', '79', '91', '84.5', '54', '53.2', '52.4', '72',
       '99', '56', '85', '83.1', '51.9', '57', '81', '74', '78.5', '65',
       '66.1', '68', '58', '86', '53.5', '83', '82', '95', '78', '72.5',
       '66.6', '51.7', '90.7', '84', '75.5', '63', '53', '91.8', '58.5',
       '55.5', '77', '88', '62', '97', '63.8', '97.4', '92', '67', '71',
       '87', '78.7', '50.1', '50.4', '68.3', '99.5', '76', '59.5', '96',
       '99.8', '56.8', '79.4', '93', '89', '54.5', '96.5', '85.4', '79.2',
       '94', '58.2', '59.9', '61.6', '60.5', '82.5', '75.7', '56.2',
       '99.6', '58.8', '59.2', '74.4', '56.1', '86.7', '53.1', '90.8',
       '50.5', '75.3', '59', '58.4', '85.1', '79.9', '68.2', '51.8',
       '64.4', '64', '56.4', '76.2', '100', '88.5', '98.1', '76.6',
       '87.4', '71.5', '84.7', '60.2', '64.6', '80.3', '89.7', '66',
       '67.3', '76.4', '73', '77.8', '76.8', '86.5', '62.8', '94.3',
       '94.8', '71.9', '72.1', '84.8', '95.2', '63.5', '98.3', '65.6',
       '52.5', '62.5', '65.8', '50.9', '74.9', '79.3', '85.5', '65.4',
       '75.9', '55.3', '70.6', '93.5', '60.9', '91.5', '59.4', '86.1',
       '61.7', '89.8', '88.6', '67.8', '64.7', '90.5', '67.9', '51.6',
       '77.1', '62.4', '74.1', '58.1', '58.7', '69', '93.6', '57.5',
       '82.9', '83.5', '79.7', '90.4', '70.3', '54.6', '56.7', '95.5',
       '52.6', '76.5', '69.6', '81.6', '94.5', '73.1', '71.7', '75.1',
       '55.4', '88.9', '88.8', '77.5', '59.7', '89.4', '59.8', '63.7',
       '82.1', '61.9', '92.4', '73.9', '51.1', '61.5', '65.9', '70.4',
       '56.6', '62.9', '83.8', '92.8', '84.6', '59.1', '78.2', '64.2',
       '69.2', '94.7', '58.3', '70.7', '97.6', '75.8', '51.2', '86.9',
       '68.4', '72.8', '57.2', '90.6', '65.5', '80.8', '62.1', '69.5',
       '92.5', '62.3', '82.8', '60.8', '71.1', '64.3', '86.3', '60.4',
       '79.8', '52.8', '61.2', '60.3', '77.7', '53.6', '70.8', '88.1',
       '68.9', '72.4', '85.6', '72.6', '97.7', '52.7', '84.9', '98.6',
       '78.9', '72.2', '98.4', '62.6', '55.1', '52.1', '99.9', '76.3',
       '95.6', '65.1', '81.4', '74.2', '65.3', '92.3', '60.6', '76.9',
       '78.1', '51.3', '63.3', '54.2', '97.5', '99.3', '54.8', '73.4',
       '64.1', '63.9', '73.5', '66.5', '87.5', '80.2', '77.3', '70.2',
       '69.7', '59.6', '83.7', '71.8', '65.7', '78.8', '83.4', '58.9',
       '61.3', '1.49', '1.12', '1.26', '1.32', '1.50', '1.35', '1.10',
       '1.07', '1.37', '1.11', '1.01', '1.13', '1.39', '1.15', '1.05',
       '1.30', '1.20', '1.48', '1.03', '1.33', '1.42', '1.18', '1.24',
       '1.23', '1.17', '1.25', '1.40', '1.28', '1.22', '1.31', '1.09',
       '1.45', '1.36', '1.19', '1.21', '1.44', '1.14', '1.29', '1.34',
       '1.02', '1.43', '1.06', '1.47', '1.04', '1.41', '1.46', '1.27',
       '1.08', '1.16', '1.38', '2.30', '1.54', '2.84', '2.52', '2.19',
       '2.80', '3.45', '1.80', '1.62', '2.25', '7.50', '1.70', '2.47',
       '1.60', '1.65', '3.50', '2.85', '3.65', '12.93', '1.63', '5.50',
       '2.61', '3.20', '1.61', '1.72', '4', '5.51', '1.68', '3.41',
       '2.51', '1.51', '2.82', '1.98', '2.10', '2.98', '3', '3.30',
       '6.50', '2.34', '2.76', '3.61', '2.11', '4.99', '1.76', '2.40',
       '8.50', '5.25', '4.10', '1.89', '2.50', '2.83', '2.20', '3.49',
       '3.33', '18.50', '2.27', '31.50', '1.53', '1.94', '2.15', '2.55',
       '4.50', '4.08', '12.50', '1.59', '1.55', '5.18', '3.51', '1.81',
       '3.80', '534.44', '3.03', '6.96', '1.75', '3.25', '1.52', '3.55',
       '2.72', '1.90', '6.60', '1.95', '2.73', '3.11', '3.75', '2.17',
       '2.32', '2.69', '3.10', '3.31', '2.60', '1.58', '2.75', '3.60',
       '3.12', '146.33', '1.71', '4.35', '2.95', '2.70', '3.70', '2.26',
       '5.04', '2.46', '2.43', '1.86', '2.77', '4.71', '4.65', '1.77',
       '2.90', '2.36', '2.03', '1.84', '6.30', '2.04', '7.20', '4.03',
       '1.73', '3.08', '2.92', '3.53', '3.23', '1.66', '4.07', '6.80',
       '3.35', '3.22', '5.55', '1.82', '2.59', '2.07', '1.88', '2.56',
       '9.22', '2.88', '2.18', '1.85', '3.96', '3.99', '2.21', '2.01',
       '3.01', '3.26', '11.55', '2.71', '2.66', '3.63', '2.28', '1.91',
       '1.56', '1.96', '3.32', '7.58', '4.75', '1.93', '2.37', '1.69',
       '5.52', '2.16', '1.97', '8.79', '2.62', '2.39', '1.99', '4.31',
       '1.79', '10.09', '5.57', '4.25', '3.34', '3.15', '8.13', '1.87',
       '6.53', '7.95', '2.33', '4.30', '2.48', '3.19', '3.74', '4.20',
       '4.42', '1.92', '3.04', '4.73', '3.95', '2.35', '3.18', '1.74',
       '1.64', '2.81', '2.58', '3.39', '4.60', '4.72', '4.01', '1.57',
       '8.60', '6.47', '3.93', '1.83', '2.68', '2.54', '2.24', '3.05',
       '3.48', '2.99', '3.97', '3.40', '4.23', '6.76', '3.58', '4.80',
       '2.05', '2.97', '4.51', '3.90', '3.13', '3.36', '16.50', '2.02',
       '1.67', '2.14', '5.72', '2.79', '2.13', '3.02', '2.57', '2.08',
       '7.60', '4.24', '5.48', '2.78', '2.22', '2.87', '5.12', '3.54',
       '4.53', '6.10', '3.76', '4.16', '3.92', '2.41', '4.38', '5.36',
       '5.40', '7.19', '3.24', '4.32', '4.05', '3.59', '6.37', '3.27',
       '7.22', '3.21', '4.14', '4.41', '7.65', '5.20', '4.39', '4.68',
       '4.67', '5.60', '6.08'], dtype=object)

In [62]:
fu['price'].unique()

array(['33.8', '45.4', '44.6', '47', '45', '43.2', '42.1', '44.1', '44.3',
       '40', '44', '12.5', '50', '35.8', '26.5', '42', '43', '20', '37',
       '29', '38', '13', '46.5', '41.6', '33.5', '42.5', '48', '32', '35',
       '46.2', '38.5', '23', '24', '28', '35.7', '36.5', '36', '43.6',
       '25', '41', '28.5', '9', '30', '39.5', '21.5', '10.5', '18', '10',
       '23.5', '16.3', '13.5', '49', '21', '39', '16', '27', '15', '39.9',
       '7.5', '12.8', '9.5', '31.5', '46', '6', '34', '22', '19', '8.5',
       '11', '16.5', '17', '14', '33', '20.5', '21.7', '27.5', '12', '26',
       '7.7', '44.8', '34.9', '19.5', '18.5', '48.5', '49.9', '26.7',
       '18.2', '24.5', '46.1', '14.2', '47.5', '9.3', '5', '8.9', '14.5',
       '37.6', '25.5', '29.5', '1.5', '26.8', '31', '22.5', '24.9',
       '40.4', '15.3', '7', '32.5', '1', '43.8', '14.4', '10.3', '40.5',
       '34.8', '39.8', '25.8', '3.5', '21.3', '8', '38.1', '15.5', '25.1',
       '37.9', '29.1', '1.3', '18.4', '14.1', '29.9', '45.2', '37.5',
       '32.7', '17.5', '48.8', '23.2', '4.5', '25.2', '27.2',
       'Call for Price', '39.7', '43.7', '49.5', '2', '46.9', '19.8',
       '26.9', '21.6', '33.9', '34.7', '44.5', '41.3', '48.6', '45.5',
       '49.3', '43.1', '46.4', '42.2', '34.5', '28.2', '42.8', '45.3',
       '34.4', '30.5', '44.2', '48.2', '49.7', '47.8', '34.6', '49.1',
       '35.3', '45.1', '41.5', '26.4', '37.2', '46.3', '30.4', '47.1',
       '41.7', '33.4', '40.7', '36.8', '42.7', '30.6', '43.4', '38.7',
       '33.2', '34.3', '39.2', '43.9', '35.2', '31.6', '41.1', '44.9',
       '25.9', '42.3', '25.3', '36.1', '25.7', '45.6', '35.1', '36.4',
       '42.4', '46.7', '20.1', '34.1', '16.4', '43.5', '19.9', '38.2',
       '35.5', '67.7', '55.6', '98', '62.2', '69.4', '70', '56.5', '57.4',
       '92.9', '57.1', '55.7', '79.1', '65.2', '80.5', '90', '75', '52',
       '75.4', '74.5', '69.3', '60', '67.5', '51.5', '67.4', '55', '50.3',
       '66.3', '80', '1 Cr', '50.6', '61', '51', '50.8', '79', '91',
       '84.5', '54', '53.2', '52.4', '72', '99', '56', '85', '83.1',
       '51.9', '57', '81', '74', '78.5', '65', '66.1', '68', '58', '86',
       '53.5', '83', '82', '95', '78', '72.5', '66.6', '51.7', '90.7',
       '84', '75.5', '63', '53', '91.8', '58.5', '55.5', '77', '88', '62',
       '97', '63.8', '97.4', '92', '67', '71', '87', '78.7', '50.1',
       '50.4', '68.3', '99.5', '76', '59.5', '96', '99.8', '56.8', '79.4',
       '93', '89', '54.5', '96.5', '85.4', '79.2', '94', '58.2', '59.9',
       '61.6', '60.5', '82.5', '75.7', '56.2', '99.6', '58.8', '59.2',
       '74.4', '56.1', '86.7', '53.1', '90.8', '50.5', '75.3', '59',
       '58.4', '85.1', '79.9', '68.2', '51.8', '64.4', '64', '56.4',
       '76.2', '100', '88.5', '98.1', '76.6', '87.4', '71.5', '84.7',
       '60.2', '64.6', '80.3', '89.7', '66', '67.3', '76.4', '73', '77.8',
       '76.8', '86.5', '62.8', '94.3', '94.8', '71.9', '72.1', '84.8',
       '95.2', '63.5', '98.3', '65.6', '52.5', '62.5', '65.8', '50.9',
       '74.9', '79.3', '85.5', '65.4', '75.9', '55.3', '70.6', '93.5',
       '60.9', '91.5', '59.4', '86.1', '61.7', '89.8', '88.6', '67.8',
       '64.7', '90.5', '67.9', '51.6', '77.1', '62.4', '74.1', '58.1',
       '58.7', '69', '93.6', '57.5', '82.9', '83.5', '79.7', '90.4',
       '70.3', '54.6', '56.7', '95.5', '52.6', '76.5', '69.6', '81.6',
       '94.5', '73.1', '71.7', '75.1', '55.4', '88.9', '88.8', '77.5',
       '59.7', '89.4', '59.8', '63.7', '82.1', '61.9', '92.4', '73.9',
       '51.1', '61.5', '65.9', '70.4', '56.6', '62.9', '83.8', '92.8',
       '84.6', '59.1', '78.2', '64.2', '69.2', '94.7', '58.3', '70.7',
       '97.6', '75.8', '51.2', '86.9', '68.4', '72.8', '57.2', '90.6',
       '65.5', '80.8', '62.1', '69.5', '92.5', '62.3', '82.8', '60.8',
       '71.1', '64.3', '86.3', '60.4', '79.8', '52.8', '61.2', '60.3',
       '77.7', '53.6', '70.8', '88.1', '68.9', '72.4', '85.6', '72.6',
       '97.7', '52.7', '84.9', '98.6', '78.9', '72.2', '98.4', '62.6',
       '55.1', '52.1', '99.9', '76.3', '95.6', '65.1', '81.4', '74.2',
       '65.3', '92.3', '60.6', '76.9', '78.1', '51.3', '63.3', '54.2',
       '97.5', '99.3', '54.8', '73.4', '64.1', '63.9', '73.5', '66.5',
       '87.5', '80.2', '77.3', '70.2', '69.7', '59.6', '83.7', '71.8',
       '65.7', '78.8', '83.4', '58.9', '61.3', '1.49 Cr', '1.12 Cr',
       '1.26 Cr', '1.32 Cr', '1.50 Cr', '1.35 Cr', '1.10 Cr', '1.07 Cr',
       '1.37 Cr', '1.11 Cr', '1.01 Cr', '1.13 Cr', '1.39 Cr', '1.15 Cr',
       '1.05 Cr', '1.30 Cr', '1.20 Cr', '1.48 Cr', '1.03 Cr', '1.33 Cr',
       '1.42 Cr', '1.18 Cr', '1.24 Cr', '1.23 Cr', '1.17 Cr', '1.25 Cr',
       '1.40 Cr', '1.28 Cr', '1.22 Cr', '1.31 Cr', '1.09 Cr', '1.45 Cr',
       '1.36 Cr', '1.19 Cr', '1.21 Cr', '1.44 Cr', '1.14 Cr', '1.29 Cr',
       '1.34 Cr', '1.02 Cr', '1.43 Cr', '1.06 Cr', '1.47 Cr', '1.04 Cr',
       '1.41 Cr', '1.46 Cr', '1.27 Cr', '1.08 Cr', '1.16 Cr', '1.38 Cr',
       '2.30 Cr', '1.54 Cr', '2.84 Cr', '2.52 Cr', '2.19 Cr', '7 Cr',
       '2.80 Cr', '3.45 Cr', '1.80 Cr', '1.62 Cr', '2 Cr', '2.25 Cr',
       '7.50 Cr', '1.70 Cr', '10 Cr', '2.47 Cr', '1.60 Cr', '1.65 Cr',
       '3.50 Cr', '2.85 Cr', '3.65 Cr', '12.93 Cr', '1.63 Cr', '5.50 Cr',
       '2.61 Cr', '3.20 Cr', '1.61 Cr', '1.72 Cr', '4 Cr', '9 Cr',
       '5.51 Cr', '5 Cr', '1.68 Cr', '3.41 Cr', '2.51 Cr', '1.51 Cr',
       '2.82 Cr', '1.98 Cr', '2.10 Cr', '2.98 Cr', '6 Cr', '3 Cr',
       '3.30 Cr', '6.50 Cr', '2.34 Cr', '2.76 Cr', '3.61 Cr', '2.11 Cr',
       '4.99 Cr', '1.76 Cr', '2.40 Cr', '8.50 Cr', '5.25 Cr', '4.10 Cr',
       '1.89 Cr', '2.50 Cr', '2.83 Cr', '2.20 Cr', '3.49 Cr', '3.33 Cr',
       '18.50 Cr', '2.27 Cr', '31.50 Cr', '1.53 Cr', '1.94 Cr', '41 Cr',
       '2.15 Cr', '2.55 Cr', '4.50 Cr', '4.08 Cr', '12.50 Cr', '1.59 Cr',
       '1.55 Cr', '5.18 Cr', '3.51 Cr', '1.81 Cr', '3.80 Cr', '534.44 Cr',
       '3.03 Cr', '6.96 Cr', '1.75 Cr', '3.25 Cr', '1.52 Cr', '12 Cr',
       '3.55 Cr', '2.72 Cr', '1.90 Cr', '6.60 Cr', '1.95 Cr', '2.73 Cr',
       '3.11 Cr', '3.75 Cr', '2.17 Cr', '2.32 Cr', '2.69 Cr', '55 Cr',
       '3.10 Cr', '3.31 Cr', '2.60 Cr', '1.58 Cr', '2.75 Cr', '15 Cr',
       '3.60 Cr', '3.12 Cr', '146.33 Cr', '1.71 Cr', '4.35 Cr', '2.95 Cr',
       '20 Cr', '2.70 Cr', '3.70 Cr', '2.26 Cr', '14 Cr', '5.04 Cr',
       '2.46 Cr', '2.43 Cr', '1.86 Cr', '2.77 Cr', '4.71 Cr', '4.65 Cr',
       '1.77 Cr', '2.90 Cr', '2.36 Cr', '2.03 Cr', '1.84 Cr', '6.30 Cr',
       '2.04 Cr', '7.20 Cr', '4.03 Cr', '1.73 Cr', '3.08 Cr', '2.92 Cr',
       '3.53 Cr', '3.23 Cr', '1.66 Cr', '4.07 Cr', '6.80 Cr', '3.35 Cr',
       '3.22 Cr', '5.55 Cr', '1.82 Cr', '2.59 Cr', '2.07 Cr', '1.88 Cr',
       '2.56 Cr', '9.22 Cr', '2.88 Cr', '2.18 Cr', '1.85 Cr', '3.96 Cr',
       '3.99 Cr', '2.21 Cr', '2.01 Cr', '3.01 Cr', '3.26 Cr', '11.55 Cr',
       '2.71 Cr', '2.66 Cr', '3.63 Cr', '2.28 Cr', '1.91 Cr', '1.56 Cr',
       '1.96 Cr', '3.32 Cr', '7.58 Cr', '4.75 Cr', '1.93 Cr', '2.37 Cr',
       '1.69 Cr', '5.52 Cr', '2.16 Cr', '1.97 Cr', '8.79 Cr', '2.62 Cr',
       '2.39 Cr', '1.99 Cr', '4.31 Cr', '1.79 Cr', '10.09 Cr', '5.57 Cr',
       '4.25 Cr', '3.34 Cr', '3.15 Cr', '8.13 Cr', '1.87 Cr', '6.53 Cr',
       '7.95 Cr', '2.33 Cr', '4.30 Cr', '2.48 Cr', '3.19 Cr', '3.74 Cr',
       '4.20 Cr', '4.42 Cr', '1.92 Cr', '3.04 Cr', '4.73 Cr', '3.95 Cr',
       '2.35 Cr', '3.18 Cr', '1.74 Cr', '1.64 Cr', '2.81 Cr', '2.58 Cr',
       '3.39 Cr', '4.60 Cr', '4.72 Cr', '4.01 Cr', '1.57 Cr', '8.60 Cr',
       '6.47 Cr', '3.93 Cr', '1.83 Cr', '2.68 Cr', '2.54 Cr', '2.24 Cr',
       '3.05 Cr', '3.48 Cr', '2.99 Cr', '3.97 Cr', '3.40 Cr', '4.23 Cr',
       '6.76 Cr', '3.58 Cr', '8 Cr', '4.80 Cr', '2.05 Cr', '2.97 Cr',
       '4.51 Cr', '3.90 Cr', '3.13 Cr', '3.36 Cr', '16.50 Cr', '2.02 Cr',
       '1.67 Cr', '2.14 Cr', '5.72 Cr', '2.79 Cr', '2.13 Cr', '3.02 Cr',
       '2.57 Cr', '2.08 Cr', '7.60 Cr', '4.24 Cr', '5.48 Cr', '2.78 Cr',
       '2.22 Cr', '2.87 Cr', '5.12 Cr', '3.54 Cr', '4.53 Cr', '6.10 Cr',
       '3.76 Cr', '4.16 Cr', '3.92 Cr', '2.41 Cr', '4.38 Cr', '5.36 Cr',
       '5.40 Cr', '7.19 Cr', '3.24 Cr', '4.32 Cr', '4.05 Cr', '3.59 Cr',
       '6.37 Cr', '3.27 Cr', '7.22 Cr', '3.21 Cr', '4.14 Cr', '4.41 Cr',
       '7.65 Cr', '5.20 Cr', '4.39 Cr', '4.68 Cr', '4.67 Cr', '5.60 Cr',
       '6.08 Cr'], dtype=object)

In [63]:
out=[]
for i in fu['price']:
    if 'Lac' in i:
        out.append(float(i.strip('₹ Lac'))*100000)
    elif 'Cr' in i:
        out.append(float(i.strip('₹ Cr'))*10000000)
    else:
        np.nan
out

[10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 14900000.0,
 11200000.000000002,
 11200000.000000002,
 12600000.0,
 13200000.0,
 15000000.0,
 13500000.0,
 11000000.0,
 10700000.0,
 13700000.000000002,
 11200000.000000002,
 11100000.000000002,
 10100000.0,
 11299999.999999998,
 13899999.999999998,
 11500000.0,
 10500000.0,
 13000000.0,
 13500000.0,
 12600000.0,
 12000000.0,
 11500000.0,
 14800000.0,
 10000000.0,
 10300000.0,
 13300000.0,
 12000000.0,
 10300000.0,
 14200000.0,
 11800000.0,
 12400000.0,
 12300000.0,
 11700000.0,
 10700000.0,
 10500000.0,
 10100000.0,
 12500000.0,
 12300000.0,
 10000000.0,
 10500000.0,
 15000000.0,
 14000000.0,
 12000000.0,
 12600000.0,
 10000000.0,
 15000000.0,
 15000000.0,
 12500000.0,
 14900000.0,
 15000000.0,
 10000000.0,
 11100000.000000002,
 10000000.0,
 13200000.0,
 15000000.0,
 11100000.000000002,
 12500000.0,
 12500000.0,
 15000000.0,
 10000000.0,
 11100000.000000002,
 12800000.0,
 12200000.0,
 13100000.0,
 11500000.0,
 12000000.0,
 10000000.0,
 10900000.0,
 12500000.0,
 10000000.0,
 12500000.0,
 13000000.0,
 15000000.0,
 10000000.0,
 12500000.0,
 12500000.0,
 12500000.0,
 14000000.0,
 14500000.0,
 13500000.0,
 14000000.0,
 11000000.0,
 12000000.0,
 11000000.0,
 10000000.0,
 11500000.0,
 13000000.0,
 15000000.0,
 10500000.0,
 12000000.0,
 13000000.0,
 11100000.000000002,
 12000000.0,
 12000000.0,
 11100000.000000002,
 11000000.0,
 13600000.000000002,
 13000000.0,
 11500000.0,
 12500000.0,
 13000000.0,
 11900000.0,
 12100000.0,
 13000000.0,
 13000000.0,
 15000000.0,
 11800000.0,
 11000000.0,
 12300000.0,
 10000000.0,
 12100000.0,
 11000000.0,
 15000000.0,
 11000000.0,
 15000000.0,
 15000000.0,
 13500000.0,
 13500000.0,
 14500000.0,
 12000000.0,
 10000000.0,
 14400000.0,
 15000000.0,
 11000000.0,
 14500000.0,
 10500000.0,
 11000000.0,
 12000000.0,
 13300000.0,
 11000000.0,
 10100000.0,
 11500000.0,
 15000000.0,
 12500000.0,
 12500000.0,
 11000000.0,
 15000000.0,
 10000000.0,
 15000000.0,
 10000000.0,
 11000000.0,
 12500000.0,
 11399999.999999998,
 11000000.0,
 12100000.0,
 12500000.0,
 10000000.0,
 11500000.0,
 11500000.0,
 13500000.0,
 12500000.0,
 14000000.0,
 10000000.0,
 11500000.0,
 12000000.0,
 15000000.0,
 10000000.0,
 15000000.0,
 11200000.000000002,
 14500000.0,
 12100000.0,
 15000000.0,
 10000000.0,
 13300000.0,
 11500000.0,
 12100000.0,
 11100000.000000002,
 11500000.0,
 12100000.0,
 13500000.0,
 14000000.0,
 15000000.0,
 11200000.000000002,
 15000000.0,
 15000000.0,
 10000000.0,
 15000000.0,
 12900000.0,
 15000000.0,
 10000000.0,
 14000000.0,
 12000000.0,
 10500000.0,
 10300000.0,
 15000000.0,
 15000000.0,
 11500000.0,
 13000000.0,
 13400000.0,
 12500000.0,
 10200000.0,
 12000000.0,
 14000000.0,
 11000000.0,
 12500000.0,
 11000000.0,
 10000000.0,
 11100000.000000002,
 12000000.0,
 14000000.0,
 12500000.0,
 14300000.0,
 11000000.0,
 14300000.0,
 12100000.0,
 12500000.0,
 11700000.0,
 10500000.0,
 10600000.0,
 12800000.0,
 10900000.0,
 10600000.0,
 10100000.0,
 11000000.0,
 12600000.0,
 12800000.0,
 10500000.0,
 12800000.0,
 12900000.0,
 10000000.0,
 10000000.0,
 10000000.0,
 13200000.0,
 10500000.0,
 14000000.0,
 12500000.0,
 11900000.0,
 10500000.0,
 13100000.0,
 14000000.0,
 13500000.0,
 14200000.0,
 13000000.0,
 11900000.0,
 11100000.000000002,
 14700000.0,
 10700000.0,
 10100000.0,
 12500000.0,
 15000000.0,
 12100000.0,
 12500000.0,
 12400000.0,
 10000000.0,
 12500000.0,
 11500000.0,
 10500000.0,
 10200000.0,
 11500000.0,
 10400000.0,
 11200000.000000002,
 11700000.0,
 13500000.0,
 12900000.0,
 13899999.999999998,
 14800000.0,
 12500000.0,
 10400000.0,
 11000000.0,
 13000000.0,
 12800000.0,
 12800000.0,
 14700000.0,
 14200000.0,
 13500000.0,
 13700000.000000002,
 11000000.0,
 14100000.0,
 10500000.0,
 12500000.0,
 11100000.000000002,
 14500000.0,
 13000000.0,
 11000000.0,
 10200000.0,
 13000000.0,
 13500000.0,
 11200000.000000002,
 13300000.0,
 10300000.0,
 10000000.0,
 11500000.0,
 12800000.0,
 14800000.0,
 13500000.0,
 12000000.0,
 11200000.000000002,
 11500000.0,
 12800000.0,
 12300000.0,
 10200000.0,
 11500000.0,
 10500000.0,
 13500000.0,
 10300000.0,
 10600000.0,
 12600000.0,
 11800000.0,
 14000000.0,
 10200000.0,
 13500000.0,
 10400000.0,
 13200000.0,
 11100000.000000002,
 10300000.0,
 14500000.0,
 14600000.0,
 11000000.0,
 12000000.0,
 13500000.0,
 14000000.0,
 14100000.0,
 14000000.0,
 13600000.000000002,
 10200000.0,
 12500000.0,
 13300000.0,
 10400000.0,
 13500000.0,
 12700000.0,
 10800000.0,
 13200000.0,
 11399999.999999998,
 13400000.0,
 12700000.0,
 14000000.0,
 10400000.0,
 11000000.0,
 13500000.0,
 13700000.000000002,
 10500000.0,
 10600000.0,
 14500000.0,
 11000000.0,
 15000000.0,
 13000000.0,
 12100000.0,
 12000000.0,
 10000000.0,
 11500000.0,
 14300000.0,
 10000000.0,
 14000000.0,
 12800000.0,
 12900000.0,
 13600000.000000002,
 10700000.0,
 14600000.0,
 12100000.0,
 14500000.0,
 10300000.0,
 13500000.0,
 13200000.0,
 12900000.0,
 12000000.0,
 14000000.0,
 12000000.0,
 13500000.0,
 14600000.0,
 14300000.0,
 14000000.0,
 13100000.0,
 13000000.0,
 14000000.0,
 11200000.000000002,
 11500000.0,
 11200000.000000002,
 12900000.0,
 10500000.0,
 14500000.0,
 13500000.0,
 14200000.0,
 10400000.0,
 10500000.0,
 13300000.0,
 13000000.0,
 13200000.0,
 13500000.0,
 15000000.0,
 13899999.999999998,
 10100000.0,
 11000000.0,
 12800000.0,
 13700000.000000002,
 12800000.0,
 13000000.0,
 12000000.0,
 12200000.0,
 14000000.0,
 11500000.0,
 11299999.999999998,
 10000000.0,
 11500000.0,
 13899999.999999998,
 12000000.0,
 13100000.0,
 13100000.0,
 10900000.0,
 10300000.0,
 12700000.0,
 11600000.0,
 12000000.0,
 12500000.0,
 10700000.0,
 13000000.0,
 14800000.0,
 13899999.999999998,
 10800000.0,
 10300000.0,
 11000000.0,
 15000000.0,
 11000000.0,
 10500000.0,
 10000000.0,
 11100000.000000002,
 11500000.0,
 11100000.000000002,
 14000000.0,
 14200000.0,
 13799999.999999998,
 13100000.0,
 12700000.0,
 10500000.0,
 13799999.999999998,
 10500000.0,
 10600000.0,
 14500000.0,
 14600000.0,
 11500000.0,
 11500000.0,
 12200000.0,
 12200000.0,
 10000000.0,
 10600000.0,
 14000000.0,
 12100000.0,
 14000000.0,
 13600000.000000002,
 11500000.0,
 10400000.0,
 10900000.0,
 13500000.0,
 13799999.999999998,
 14400000.0,
 10200000.0,
 12000000.0,
 14700000.0,
 14500000.0,
 12100000.0,
 13500000.0,
 12400000.0,
 13000000.0,
 10500000.0,
 10500000.0,
 13899999.999999998,
 10400000.0,
 11500000.0,
 12500000.0,
 13500000.0,
 14000000.0,
 11900000.0,
 10700000.0,
 13400000.0,
 13700000.000000002,
 14400000.0,
 14100000.0,
 10000000.0,
 12200000.0,
 12600000.0,
 14800000.0,
 10500000.0,
 14400000.0,
 11500000.0,
 14100000.0,
 11100000.000000002,
 14400000.0,
 10700000.0,
 12800000.0,
 12500000.0,
 12400000.0,
 10400000.0,
 14000000.0,
 14400000.0,
 10000000.0,
 10000000.0,
 10400000.0,
 10800000.0,
 14000000.0,
 11200000.000000002,
 12700000.0,
 11500000.0,
 11200000.000000002,
 10100000.0,
 12200000.0,
 13200000.0,
 14100000.0,
 10900000.0,
 11299999.999999998,
 14000000.0,
 14000000.0,
 12100000.0,
 13500000.0,
 11500000.0,
 11600000.0,
 12600000.0,
 11000000.0,
 11000000.0,
 14200000.0,
 12800000.0,
 12900000.0,
 12500000.0,
 10500000.0,
 10000000.0,
 10600000.0,
 13700000.000000002,
 10000000.0,
 10400000.0,
 10000000.0,
 10600000.0,
 10000000.0,
 12100000.0,
 13899999.999999998,
 10400000.0,
 14000000.0,
 11200000.000000002,
 12000000.0,
 11900000.0,
 11500000.0,
 12900000.0,
 14900000.0,
 10500000.0,
 13899999.999999998,
 13200000.0,
 10000000.0,
 10200000.0,
 11299999.999999998,
 12200000.0,
 13100000.0,
 12000000.0,
 13500000.0,
 11800000.0,
 11900000.0,
 13200000.0,
 10200000.0,
 10900000.0,
 10400000.0,
 10300000.0,
 14200000.0,
 14800000.0,
 14800000.0,
 13200000.0,
 12800000.0,
 12500000.0,
 14000000.0,
 12700000.0,
 13300000.0,
 11000000.0,
 14000000.0,
 14000000.0,
 10500000.0,
 12900000.0,
 11100000.000000002,
 12700000.0,
 11500000.0,
 14800000.0,
 10100000.0,
 12500000.0,
 10400000.0,
 13500000.0,
 13200000.0,
 12500000.0,
 13000000.0,
 13500000.0,
 11000000.0,
 11700000.0,
 10400000.0,
 10100000.0,
 12400000.0,
 14100000.0,
 11800000.0,
 14500000.0,
 10000000.0,
 13300000.0,
 13000000.0,
 13300000.0,
 14600000.0,
 13600000.000000002,
 10400000.0,
 13799999.999999998,
 12400000.0,
 13600000.000000002,
 10200000.0,
 10600000.0,
 14400000.0,
 13400000.0,
 13500000.0,
 13500000.0,
 13100000.0,
 12000000.0,
 14200000.0,
 12000000.0,
 13100000.0,
 10800000.0,
 23000000.0,
 15400000.0,
 28400000.0,
 15400000.0,
 25200000.0,
 15000000.0,
 21900000.0,
 70000000.0,
 28000000.0,
 34500000.0,
 18000000.0,
 15400000.0,
 16200000.000000002,
 20000000.0,
 22500000.0,
 75000000.0,
 17000000.0,
 20000000.0,
 100000000.0,
 24700000.000000004,
 17000000.0,
 16000000.0,
 20000000.0,
 15400000.0,
 16500000.0,
 35000000.0,
 28500000.0,
 36500000.0,
 17000000.0,
 129300000.0,
 16299999.999999998,
 55000000.0,
 26100000.0,
 32000000.0,
 16100000.000000002,
 17200000.0,
 40000000.0,
 90000000.0,
 55100000.0,
 50000000.0,
 16800000.0,
 16299999.999999998,
 36500000.0,
 34100000.0,
 25099999.999999996,
 15100000.0,
 28200000.0,
 19800000.0,
 50000000.0,
 25099999.999999996,
 34100000.0,
 15000000.0,
 21000000.0,
 15000000.0,
 23000000.0,
 29800000.0,
 18000000.0,
 60000000.0,
 15000000.0,
 50000000.0,
 75000000.0,
 28500000.0,
 16000000.0,
 50000000.0,
 15000000.0,
 75000000.0,
 40000000.0,
 30000000.0,
 35000000.0,
 16500000.0,
 22500000.0,
 15000000.0,
 33000000.0,
 65000000.0,
 23400000.0,
 17000000.0,
 27599999.999999996,
 75000000.0,
 36100000.0,
 21100000.0,
 49900000.0,
 17600000.0,
 20000000.0,
 24000000.0,
 85000000.0,
 30000000.0,
 52500000.0,
 20000000.0,
 41000000.0,
 18900000.0,
 25000000.0,
 28300000.0,
 15000000.0,
 25099999.999999996,
 22000000.0,
 30000000.0,
 35000000.0,
 25099999.999999996,
 34900000.0,
 33300000.0,
 185000000.0,
 22700000.0,
 315000000.0,
 22500000.0,
 17000000.0,
 15300000.0,
 19400000.0,
 16200000.000000002,
 410000000.0,
 15000000.0,
 21500000.0,
 70000000.0,
 25500000.0,
 45000000.0,
 23000000.0,
 28500000.0,
 22500000.0,
 40800000.0,
 125000000.0,
 15900000.0,
 20000000.0,
 22000000.0,
 50000000.0,
 15500000.0,
 51800000.0,
 35100000.0,
 16000000.0,
 25000000.0,
 15000000.0,
 18100000.0,
 38000000.0,
 5344400000.000001,
 50000000.0,
 45000000.0,
 30299999.999999996,
 18000000.0,
 20000000.0,
 15000000.0,
 15000000.0,
 15000000.0,
 69600000.0,
 70000000.0,
 17000000.0,
 20000000.0,
 17500000.0,
 45000000.0,
 15000000.0,
 32500000.0,
 20000000.0,
 20000000.0,
 15200000.0,
 120000000.0,
 20000000.0,
 70000000.0,
 70000000.0,
 25000000.0,
 15000000.0,
 25000000.0,
 25099999.999999996,
 15000000.0,
 15100000.0,
 35500000.0,
 27200000.000000004,
 32500000.0,
 15000000.0,
 16500000.0,
 19000000.0,
 30000000.0,
 66000000.0,
 50000000.0,
 19500000.0,
 50000000.0,
 25099999.999999996,
 27300000.0,
 20000000.0,
 31100000.0,
 20000000.0,
 16500000.0,
 37500000.0,
 40000000.0,
 21000000.0,
 15000000.0,
 18900000.0,
 21700000.0,
 100000000.0,
 20000000.0,
 15500000.0,
 25000000.0,
 25000000.0,
 18000000.0,
 20000000.0,
 23200000.0,
 50000000.0,
 60000000.0,
 26900000.0,
 30000000.0,
 550000000.0,
 31000000.0,
 15500000.0,
 33100000.0,
 15000000.0,
 15000000.0,
 16500000.0,
 26000000.0,
 25000000.0,
 35000000.0,
 35000000.0,
 15800000.0,
 15500000.0,
 15900000.0,
 15100000.0,
 17000000.0,
 15000000.0,
 25099999.999999996,
 27500000.0,
 20000000.0,
 150000000.0,
 36000000.0,
 17000000.0,
 31200000.0,
 35000000.0,
 32500000.0,
 55100000.0,
 90000000.0,
 25099999.999999996,
 15100000.0,
 1463300000.0000002,
 35500000.0,
 15000000.0,
 15000000.0,
 15000000.0,
 19000000.0,
 32500000.0,
 21000000.0,
 66000000.0,
 15000000.0,
 22500000.0,
 25099999.999999996,
 36500000.0,
 50000000.0,
 100000000.0,
 35000000.0,
 17100000.0,
 22000000.0,
 50000000.0,
 45000000.0,
 35000000.0,
 35100000.0,
 15000000.0,
 20000000.0,
 43500000.0,
 17500000.0,
 29500000.0,
 22500000.0,
 33000000.0,
 200000000.0,
 19500000.0,
 31000000.0,
 25000000.0,
 20000000.0,
 15000000.0,
 27000000.0,
 15000000.0,
 27500000.0,
 17500000.0,
 70000000.0,
 22000000.0,
 70000000.0,
 27200000.000000004,
 16299999.999999998,
 37000000.0,
 17100000.0,
 22000000.0,
 16500000.0,
 22599999.999999996,
 140000000.0,
 50400000.0,
 24600000.0,
 24300000.0,
 75000000.0,
 100000000.0,
 18600000.0,
 15200000.0,
 27700000.0,
 55100000.0,
 47100000.0,
 15800000.0,
 150000000.0,
 16299999.999999998,
 16800000.0,
 46500000.0,
 17700000.0,
 29000000.0,
 15400000.0,
 19400000.0,
 24000000.0,
 75000000.0,
 16500000.0,
 22500000.0,
 23600000.0,
 15000000.0,
 37500000.0,
 27500000.0,
 20299999.999999996,
 37500000.0,
 20000000.0,
 16000000.0,
 18400000.0,
 21500000.0,
 19000000.0,
 16299999.999999998,
 63000000.0,
 20400000.0,
 72000000.0,
 35000000.0,
 40300000.0,
 17300000.0,
 22599999.999999996,
 22000000.0,
 30800000.0,
 24600000.0,
 29200000.0,
 35300000.0,
 16200000.000000002,
 32300000.0,
 16600000.0,
 40700000.0,
 30000000.0,
 27500000.0,
 15900000.0,
 68000000.0,
 33500000.0,
 32200000.000000004,
 55500000.0,
 18200000.0,
 25900000.0,
 30000000.0,
 15500000.0,
 20700000.0,
 27000000.0,
 16200000.000000002,
 25099999.999999996,
 15100000.0,
 52500000.0,
 17600000.0,
 18800000.0,
 25600000.0,
 92200000.0,
 28800000.0,
 28000000.0,
 21800000.0,
 18500000.0,
 39600000.0,
 15100000.0,
 39900000.0,
 45000000.0,
 19400000.0,
 22100000.0,
 21000000.0,
 20099999.999999996,
 15800000.0,
 49900000.0,
 30099999.999999996,
 ...]

In [68]:
#i=i.strip('')
#f=float(i)
#out.append(f*100000)