In [1]:
import pandas as pd
import numpy as np
#PANDAS
#IMPORTING the datasets from multiple sources like sql,csv,excel etc
#Data Cleaning --> handling missing,invalid values
#size mutability --> add or delete columns or rows
#Reshaping & pivoting of datasets
#used for statistical analysis

In [47]:
#PANDAS

#--> Series
#--> Dataframes

# array                                                                      series
#1) array belongs to numpy                                        1) series belongs to pandas
#2) after string everything would be considered as object         2)after complex everything would be considered as object 
#3) it displays only data                                         3) it displays data,index,datatype
#4) np.array(collectiions)                                        4) pd.Series(collection)

In [48]:
s=pd.Series([4,5,6,6,4.567,3-2j,True,'hello'],index=['a','b','c','d','e','f','g','h'],name='values')
s
s.loc[['a','c','e','f']]

a         4
c         6
e     4.567
f    (3-2j)
Name: values, dtype: object

In [49]:
d={'apple':100,'banana':3000,'carrot':200}
fru=pd.Series(d)
fru

apple      100
banana    3000
carrot     200
dtype: int64

In [50]:
d={'kk':20,'kalo':22,'singham':25,'goku':23,'luffy':19,'naruto':29,'sasuke':28,'zoro':20,'sanji':21}
s=pd.Series(d,name='____age')
s


#loc & iloc i
# loc --> Label based Indexing:
#syntax:  var.loc[index]
#         var.loc[[index_1,index_2,....]]
#         var.loc[SV:EV:UP]

#iloc --> location based indexing
#         var.iloc[index] 
#         var.iloc[[index_1,index_2,....]]
#         var.iloc[SV:EV:UP]

s.loc[['kk','singham','naruto','zoro']]

s.loc['kalo':'zoro':2]
s.loc['kalo':'zoro']
s.loc['kalo'::]
s.loc[:'sanji']
s.loc[::-1]



s.iloc[1]
s.iloc[[2,3,5,7]]
s.iloc[1:9:2]
s.iloc[::-1]
s.iloc[:9]

kk         20
kalo       22
singham    25
goku       23
luffy      19
naruto     29
sasuke     28
zoro       20
sanji      21
Name: ____age, dtype: int64

In [51]:
#filtering conditions
#syntax
#         var[condition]

s[s>20]

s[(s>20) & (s<25)]
s[(s % 5==0)]

kk         20
singham    25
zoro       20
Name: ____age, dtype: int64

In [52]:
#Dataframe
#syntax:-  var=pd.DataFrame(dictionary)

d={'ename':['yash','rahul','harsh','siddhant','sumeet'],
   'Eid':[101,102,103,104,105],
   'Salary':['8LPA','5.6LPA','3LPA','7LPA','10LPA']}

df=pd.DataFrame(d)
df



s={'Sname':['yash','rahul','harsh','siddhant','sumeet'],
   'Sid':[101,102,103,104,105],
   'Course':['BCA','Btech','MCA','Bcom','BBA']}

df=pd.DataFrame(s)
df
df['Sname']

0        yash
1       rahul
2       harsh
3    siddhant
4      sumeet
Name: Sname, dtype: object

In [53]:
# to access any particular column
#syntax
#  var['col_name']

s={'Sname':['yash','rahul','harsh','siddhant','sumeet'],
   'Sid':[101,102,103,104,105],
   'Course':['BCA','Btech','MCA','Bcom','BBA']}

df=pd.DataFrame(s)
df

#Indexing and Slicing of Dataframe

df[::-1]
df[1:3:]
df['Sname']
df['Sname'][0]
df['Sname'][0:3]

0     yash
1    rahul
2    harsh
Name: Sname, dtype: object

In [54]:
#to add new column in exixsting dataframe
#syntax   var['new_col']=[equal number of value present in existing dataframe]
df['age']=[20,21,19,20,22]
df['course_fee']=[50000,60000,70000,80000,90000]
df

      Sname  Sid Course  age  course_fee
0      yash  101    BCA   20       50000
1     rahul  102  Btech   21       60000
2     harsh  103    MCA   19       70000
3  siddhant  104   Bcom   20       80000
4    sumeet  105    BBA   22       90000

In [55]:
#to read the csv file
#syntax:-->    var=pd.read_csv('file_path'/'file_name')

tips=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/tips.csv')
tips

URLError: <urlopen error [Errno 11001] getaddrinfo failed>

In [ ]:
ti=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/titanic.csv')
ti

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0
...,...,...,...,...,...,...,...,...,...,...,...
1304,3,"Zabour, Miss. Hileni",female,14.5000,1,0,2665,14.4542,NaN,C,0
1305,3,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,0
1306,3,"Zakarian, Mr. Mapriededer",male,26.5000,0,0,2656,7.2250,NaN,C,0
1307,3,"Zakarian, Mr. Ortin",male,27.0000,0,0,2670,7.2250,NaN,C,0
1308,3,"Zimmerman, Mr. Leo",male,29.0000,0,0,315082,7.8750,NaN,S,0

In [ ]:
hr=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/hr_data.csv')
hr

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low
...,...,...,...,...,...,...,...,...,...
14994,87670,2,151,3,0,1,0,support,low
14995,87673,2,160,3,0,1,0,support,low
14996,87679,2,143,3,0,1,0,support,low
14997,87681,6,280,4,0,1,0,support,low
14998,87684,2,158,3,0,1,0,support,low

In [ ]:
wq=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/winequalityN.csv')
wq

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,white,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6492,red,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6494,red,6.3,0.510,0.13,2.3,0.076,29.0,40.0,0.99574,3.42,0.75,11.0,6
6495,red,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [ ]:
amz=pd.read_csv('https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Practice/amazon_fires.csv',encoding='ISO-8859-1')
amz

       ano       mes     estado   numero  encontro
0     1998   Janeiro       Acre  0 Fires  1/1/1998
1     1999   Janeiro       Acre  0 Fires  1/1/1999
2     2000   Janeiro       Acre  0 Fires  1/1/2000
3     2001   Janeiro       Acre  0 Fires  1/1/2001
4     2002   Janeiro       Acre  0 Fires  1/1/2002
...    ...       ...        ...      ...       ...
6449  2012  Dezembro  Tocantins      128  1/1/2012
6450  2013  Dezembro  Tocantins       85  1/1/2013
6451  2014  Dezembro  Tocantins      223  1/1/2014
6452  2015  Dezembro  Tocantins      373  1/1/2015
6453  2016  Dezembro  Tocantins      119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
amz.head()#it is ude to display top five rows of the dataframe

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [ ]:
amz.tail()# it is use to display last five rows of the dataframe

       ano       mes     estado numero  encontro
6449  2012  Dezembro  Tocantins    128  1/1/2012
6450  2013  Dezembro  Tocantins     85  1/1/2013
6451  2014  Dezembro  Tocantins    223  1/1/2014
6452  2015  Dezembro  Tocantins    373  1/1/2015
6453  2016  Dezembro  Tocantins    119  1/1/2016

In [ ]:
amz.head(11)#var.head(n) it is use to display n number of rows from top

     ano      mes estado    numero  encontro
0   1998  Janeiro   Acre   0 Fires  1/1/1998
1   1999  Janeiro   Acre   0 Fires  1/1/1999
2   2000  Janeiro   Acre   0 Fires  1/1/2000
3   2001  Janeiro   Acre   0 Fires  1/1/2001
4   2002  Janeiro   Acre   0 Fires  1/1/2002
5   2003  Janeiro   Acre  10 Fires  1/1/2003
6   2004  Janeiro   Acre   0 Fires  1/1/2004
7   2005  Janeiro   Acre  12 Fires  1/1/2005
8   2006  Janeiro   Acre   4 Fires  1/1/2006
9   2007  Janeiro   Acre   0 Fires  1/1/2007
10  2008  Janeiro   Acre   0 Fires  1/1/2008

In [ ]:
amz.tail(11)#it is use to display n number rows from bottom

       ano       mes     estado numero  encontro
6443  2006  Dezembro  Tocantins     15  1/1/2006
6444  2007  Dezembro  Tocantins     13  1/1/2007
6445  2008  Dezembro  Tocantins      7  1/1/2008
6446  2009  Dezembro  Tocantins     46  1/1/2009
6447  2010  Dezembro  Tocantins     72  1/1/2010
6448  2011  Dezembro  Tocantins    105  1/1/2011
6449  2012  Dezembro  Tocantins    128  1/1/2012
6450  2013  Dezembro  Tocantins     85  1/1/2013
6451  2014  Dezembro  Tocantins    223  1/1/2014
6452  2015  Dezembro  Tocantins    373  1/1/2015
6453  2016  Dezembro  Tocantins    119  1/1/2016

In [ ]:
#var.info()  it will return the overall information about dataframe
amz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   object
 2   estado    6454 non-null   object
 3   numero    6322 non-null   object
 4   encontro  6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB

In [ ]:
#var.describe()  it will return statistical information about dataframe
#it will work only on numeric columns
amz.describe()

hr.describe()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000
mean,45424.627575,3.803054,201.050337,3.498233,0.144610,0.238083,0.021268
std,25915.900127,1.232592,49.943099,1.460136,0.351719,0.425924,0.144281
min,1003.000000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000
25%,22872.500000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000
50%,45448.000000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000
75%,67480.500000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000
max,99815.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000

In [ ]:
tips.describe()

       Unnamed: 0  total_bill         tip        size
count  244.000000  244.000000  244.000000  244.000000
mean   121.500000   19.785943    2.998279    2.569672
std     70.580923    8.902412    1.383638    0.951100
min      0.000000    3.070000    1.000000    1.000000
25%     60.750000   13.347500    2.000000    2.000000
50%    121.500000   17.795000    2.900000    2.000000
75%    182.250000   24.127500    3.562500    3.000000
max    243.000000   50.810000   10.000000    6.000000

In [ ]:
#var.describe(include=object) #it will return statistical information about dataframe
tips.describe(include=object)

         sex smoker  day    time
count    244    244  244     244
unique     2      2    4       2
top     Male     No  Sat  Dinner
freq     157    151   87     176

In [ ]:
hr.describe(include=object)

       department salary
count       14999  14999
unique         10      3
top         sales    low
freq         4140   7316

In [ ]:
#var.desribe(include='all') 
hr.describe(include='all')

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
count,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999.000000,14999,14999
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,3
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sales,low
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4140,7316
mean,45424.627575,3.803054,201.050337,3.498233,0.144610,0.238083,0.021268,NaN,NaN
std,25915.900127,1.232592,49.943099,1.460136,0.351719,0.425924,0.144281,NaN,NaN
min,1003.000000,2.000000,96.000000,2.000000,0.000000,0.000000,0.000000,NaN,NaN
25%,22872.500000,3.000000,156.000000,3.000000,0.000000,0.000000,0.000000,NaN,NaN
50%,45448.000000,4.000000,200.000000,3.000000,0.000000,0.000000,0.000000,NaN,NaN
75%,67480.500000,5.000000,245.000000,4.000000,0.000000,0.000000,0.000000,NaN,NaN
max,99815.000000,7.000000,310.000000,10.000000,1.000000,1.000000,1.000000,NaN,NaN

In [ ]:
tips.describe(include='all')

,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size
count,244.000000,244.000000,244.000000,244,244,244,244,244.000000
unique,NaN,NaN,NaN,2,2,4,2,NaN
top,NaN,NaN,NaN,Male,No,Sat,Dinner,NaN
freq,NaN,NaN,NaN,157,151,87,176,NaN
mean,121.500000,19.785943,2.998279,NaN,NaN,NaN,NaN,2.569672
std,70.580923,8.902412,1.383638,NaN,NaN,NaN,NaN,0.951100
min,0.000000,3.070000,1.000000,NaN,NaN,NaN,NaN,1.000000
25%,60.750000,13.347500,2.000000,NaN,NaN,NaN,NaN,2.000000
50%,121.500000,17.795000,2.900000,NaN,NaN,NaN,NaN,2.000000
75%,182.250000,24.127500,3.562500,NaN,NaN,NaN,NaN,3.000000
max,243.000000,50.810000,10.000000,NaN,NaN,NaN,NaN,6.000000

In [ ]:
#var.shape   it will return number of rows and columns
#var['col_name'].unique()  it will return unique values of the column
#var['col_name'].value_counts()  it will return the number of occurance on each unique value present in the column
#var.columns  it will return the column names of the dataframe
#var.sample(n)  it will return n number of random rows from the dataframe
#var.sample  it will return a random row as sample from the dataset

tips.shape

hr.shape
titanic.shape
wq.shape

tips['day'].unique()
tips.sample
tips.columns
amz['mes'].unique()

hr['department'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [ ]:
hr['department'].value_counts()

department
sales          4140
technical      2720
support        2229
IT             1227
product_mng     902
marketing       858
RandD           787
accounting      767
hr              739
management      630
Name: count, dtype: int64

In [ ]:
tips['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [ ]:

wq.head()
wq['type'].value_counts()

type
white    4898
red      1599
Name: count, dtype: int64

In [ ]:
wq.columns

Index(['type', 'fixed acidity', 'volatile acidity', 'citric acid',
       'residual sugar', 'chlorides', 'free sulfur dioxide',
       'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol',
       'quality'],
      dtype='object')

In [ ]:
amz.columns

amz.sample()
hr.sample(3)

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
9523,56208,5,223,3,0,0,0,technical,low
12653,73712,2,132,3,0,1,0,technical,medium
14684,85911,2,149,3,0,1,0,sales,low

In [ ]:
#Indexing and slicing
#syntax:
# var.loc[index]
# var.loc[[index1,index2...index n]]
# var.loc[sv:ev:up,['col_name_1','col_name2',...]]

amz.loc[5]

ano             2003
mes          Janeiro
estado          Acre
numero      10 Fires
encontro    1/1/2003
Name: 5, dtype: object

In [ ]:
tips.loc[[1,144,4]]

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
1             1       10.34  1.66    Male     No   Sun  Dinner     3
144         144       16.43  2.30  Female     No  Thur   Lunch     2
4             4       24.59  3.61  Female     No   Sun  Dinner     4

In [ ]:
tips.loc[10:33:2,['smoker','day','size']]

   smoker  day  size
10     No  Sun     2
12     No  Sun     2
14     No  Sun     2
16     No  Sun     3
18     No  Sun     3
20     No  Sat     2
22     No  Sat     2
24     No  Sat     2
26     No  Sat     2
28     No  Sat     2
30     No  Sat     2
32     No  Sat     2

In [ ]:
#the only diff in loc and iloc is we can perfrom column slicing with help of 'iloc'
# loc --> ending value is included
# iloc --> ending value is not included
# var.iloc[sv:ev:up,sv:ev:up]

tips.iloc[1:44:2,1:10:3]

    total_bill smoker  size
1        10.34     No     3
3        23.68     No     2
5        25.29     No     4
7        26.88     No     4
9        14.78     No     2
11       35.26     No     4
13       18.43     No     4
15       21.58     No     2
17       16.29     No     3
19       20.65     No     3
21       20.29     No     2
23       39.42     No     4
25       17.81     No     4
27       12.69     No     2
29       19.65     No     2
31       18.35     No     4
33       20.69     No     4
35       24.06     No     3
37       16.93     No     3
39       31.27     No     3
41       17.46     No     2
43        9.68     No     2

In [ ]:
#aggregate function
#sum()
#min()
#max()
#mean()
#count()
#mode()
#median()
#syntax  :-  var['col_name'].fname()

In [ ]:
hr['number_project'].sum()
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [ ]:
hr['employee_id'].count()
tips.head()
tips['total_bill'].sum()

np.float64(4827.77)

In [ ]:
tips.head()
tips['total_bill'].sum()
tips['tip'].mean()

np.float64(2.99827868852459)

In [ ]:
hr['left'].sum()

np.int64(3571)

In [ ]:
titanic.head()
titanic['age'].mean()
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
#boolean filtering
#SYNTAX:  var[condition]

tips[tips['sex']== 'Male']['sex'].count()

np.int64(157)

In [ ]:

#num of female smoker
tips[(tips['sex']=='Female') & (tips['smoker']=='Yes')]['smoker'].count()

np.int64(33)

In [ ]:
#count of customer who prefer sun lunch
tips[(tips['day']=='Sun') & (tips['time']=='Lunch')]['size'].count()

np.int64(0)

In [ ]:

#avg tip give by customer at sat dinner
tips[(tips['time']=='Dinner') & (tips['day']=='Sat')]['tip'].mean()

np.float64(2.993103448275862)

In [ ]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [ ]:
#count of emp who are working in sales and salary is low

hr[(hr['department']=='sales') & (hr['salary']=='low')]['employee_id'].count()

np.int64(2099)

In [ ]:
#count of emp who got promotion

hr[hr['promotion_last_5years']==1]['employee_id'].count()

np.int64(319)

In [ ]:
#avg num of projects handled by IT
hr[ hr['department']=='IT']['number_project'].mean()

np.float64(3.8166259168704157)

In [ ]:
#avg number of projects for IT department

hr[hr['department']=='IT']['number_project'].mean()

np.float64(3.8166259168704157)

In [ ]:
titanic.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [ ]:
#avg age of the female who survived titanic

titanic[titanic['sex']=='female']['age'].mean()

np.float64(28.6870706185567)

In [ ]:
#what is the highest tip given by female


tips[tips['sex']=='Female']['tip'].max()

np.float64(6.5)

In [ ]:
wq.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [ ]:
#what is the avg pH level of red wine

wq[wq['type']=='red']['pH'].mean()

np.float64(3.3108641202254225)

In [ ]:
#var['col_name'].isnull()
#it will return only null values from the column 

wq['pH'].isnull()  #this will return in boolean form

0       False
1       False
2       False
3       False
4       False
        ...
6492    False
6493    False
6494    False
6495    False
6496    False
Name: pH, Length: 6497, dtype: bool

In [ ]:
wq[wq['pH'].isnull()] #this will show the full null records

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
54,white,6.8,0.200,0.59,0.9,0.147,38.0,132.0,0.99300,NaN,0.38,9.1,6
139,white,8.1,0.280,0.39,1.9,0.029,18.0,79.0,0.99230,NaN,0.52,11.8,6
440,white,6.7,0.220,0.37,1.6,0.028,24.0,102.0,0.99130,NaN,0.59,11.6,7
587,white,6.1,0.320,0.25,1.7,0.034,37.0,136.0,0.99200,NaN,0.50,10.8,7
697,white,7.5,0.310,0.51,14.8,0.039,62.0,204.0,0.99820,NaN,0.60,9.5,5
972,white,6.8,0.220,0.35,17.5,0.039,38.0,153.0,0.99940,NaN,0.42,9.0,6
4892,white,6.5,0.230,0.38,1.3,0.032,29.0,112.0,0.99298,NaN,0.54,9.7,5
6428,red,NaN,0.440,0.09,2.2,0.063,9.0,18.0,0.99444,NaN,0.69,11.3,6
6429,red,NaN,0.705,0.10,2.8,0.081,13.0,28.0,0.99631,NaN,0.66,10.2,5

In [ ]:
titanic['cabin'].isnull().sum()

np.int64(1014)

In [ ]:
amz.head()

   year   months states num_of_fires      date
0  1998  Janeiro   Acre      0 Fires  1/1/1998
1  1999  Janeiro   Acre      0 Fires  1/1/1999
2  2000  Janeiro   Acre      0 Fires  1/1/2000
3  2001  Janeiro   Acre      0 Fires  1/1/2001
4  2002  Janeiro   Acre      0 Fires  1/1/2002

In [ ]:
#encoding='ISO-8859-1

In [ ]:
titanic['age'].isna().sum()  #isnull and isna are the same

np.int64(263)

In [ ]:
#var['col_name].notnull()

amz['numero'].notnull().sum()

np.int64(6322)

In [ ]:
#Data Cleaning:
# It is a process of extracting wanted data by remove unwanted data 
#Renaming the column 
# var={'old_col_name':'new_col_name'}
# var1.rename(columns=var,inplace=True)  #inplace=True will make changes in the original dataframe

In [ ]:
d={'ano':'year','mes':'months','estado':'states','numero':'num_of_fires','encontro':'date'}
amz.rename(columns=d,inplace=True)
amz

      year    months     states num_of_fires      date
0     1998   Janeiro       Acre      0 Fires  1/1/1998
1     1999   Janeiro       Acre      0 Fires  1/1/1999
2     2000   Janeiro       Acre      0 Fires  1/1/2000
3     2001   Janeiro       Acre      0 Fires  1/1/2001
4     2002   Janeiro       Acre      0 Fires  1/1/2002
...    ...       ...        ...          ...       ...
6449  2012  Dezembro  Tocantins          128  1/1/2012
6450  2013  Dezembro  Tocantins           85  1/1/2013
6451  2014  Dezembro  Tocantins          223  1/1/2014
6452  2015  Dezembro  Tocantins          373  1/1/2015
6453  2016  Dezembro  Tocantins          119  1/1/2016

[6454 rows x 5 columns]

In [ ]:
#var.duplicated()
#it will return dubplicate rowss from the data frame
tips.duplicated().sum()

np.int64(0)

In [ ]:
titanic.duplicated().sum()
amz.duplicated()
hr.duplicated().sum()

np.int64(0)

In [ ]:
#var.drop_duplicates(inplace=True)
titanic.drop_duplicates(inplace=True)
wq.drop_duplicates(inplace=True)
wq.duplicated().sum()

titanic.duplicated().mean()

np.float64(0.0)

In [ ]:
s={'Sname':['yash','rahul','harsh','sumeet','sumeet'],
   'Sid':[101,102,103,105,105],
   'Course':['BCA','Btech','MCA','BBA','BBA']}

df=pd.DataFrame(s)
df.duplicated().sum()
df.drop_duplicates()

    Sname  Sid Course
0    yash  101    BCA
1   rahul  102  Btech
2   harsh  103    MCA
3  sumeet  105    BBA

In [ ]:
hr.shape
hr.drop_duplicates(inplace=True)
wq.duplicated().sum()
wq.shape

wq.drop_duplicates(inplace=True)

In [ ]:
#changing the data present in the column
# var = {'olddata': 'new_data'}
# #var_1 ['col_name'] =var_1['col_name'].map(var)
# -->1) When we want to change whole data prsent in the column we use map().
# 2) we can't cahneg any particular data using map() other wise it will make all the values "nan".

In [ ]:
wq.head()

wq['type'].unique()

array(['white', 'red'], dtype=object)

In [ ]:
d={'white':'white_wine','red':'red_wine'}
wq['type']=wq['type'].map(d)

In [ ]:
wq['type'].unique()

array(['white_wine', 'red_wine'], dtype=object)

In [ ]:
wq

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white_wine,7.0,0.270,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,white_wine,6.3,0.300,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,white_wine,8.1,0.280,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,white_wine,7.2,0.230,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
6,white_wine,6.2,0.320,0.16,7.0,0.045,30.0,136.0,0.99490,3.18,0.47,9.6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6491,red_wine,6.8,0.620,0.08,1.9,0.068,28.0,38.0,0.99651,3.42,0.82,9.5,6
6492,red_wine,6.2,0.600,0.08,2.0,0.090,32.0,44.0,0.99490,3.45,0.58,10.5,5
6493,red_wine,5.9,0.550,0.10,2.2,0.062,39.0,51.0,0.99512,3.52,NaN,11.2,6
6495,red_wine,5.9,0.645,0.12,2.0,0.075,32.0,44.0,0.99547,3.57,0.71,10.2,5
6496,red_wine,6.0,0.310,0.47,3.6,0.067,18.0,42.0,0.99549,3.39,0.66,11.0,6

In [ ]:
amz['months'].unique()

array(['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho',
       'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro'],
      dtype=object)

In [ ]:
c={'Janeiro':'Jan','Fevereiro':'Feb','Março':'March','Abril':'april','Maio':'May','Junho':'june','Julho':'July','Agosto':'aug','Setembro':'sep','Outubro':'Oct','Novembro':'Nov','Dezembro':'Dec'}
amz['months']=amz['months'].map(c)
amz['months'].unique()

array(['Jan', 'Feb', 'March', 'april', 'May', 'june', 'July', 'aug',
       'sep', 'Oct', 'Nov', 'Dec'], dtype=object)

In [ ]:
amz.head()

   year months states num_of_fires      date
0  1998    Jan   Acre      0 Fires  1/1/1998
1  1999    Jan   Acre      0 Fires  1/1/1999
2  2000    Jan   Acre      0 Fires  1/1/2000
3  2001    Jan   Acre      0 Fires  1/1/2001
4  2002    Jan   Acre      0 Fires  1/1/2002

In [ ]:
#applying inbuild function on data frame
#syntax:
# var['col_name']=var['col_num'].str.fname()


amz['months']=amz['months'].str.replace('Jan','january')
amz['months'].unique()

array(['january', 'Feb', 'March', 'april', 'May', 'june', 'July', 'aug',
       'sep', 'Oct', 'Nov', 'Dec'], dtype=object)

In [ ]:
amz['mes']=amz['mes'].str.upper()
amz['mes'].unique()

array(['JANUARY', 'FEB', 'MARCH', 'APRIL', 'MAY', 'JUNE', 'JULY', 'AUG',
       'SEP', 'OCT', 'NOV', 'DEC'], dtype=object)

In [ ]:
#strip():-
#It will remove the unwanted data from the dataframe 
#syntax:
# var['col_name'] =var['col_name'].str.strip('unwanted_data)


amz['num_of_fires'].unique()

array(['0 Fires', '10 Fires', '12 Fires', ..., '2.032', '833', '623'],
      shape=(1729,), dtype=object)

In [ ]:
amz['num_of_fires']=amz['num_of_fires'].str.strip(' Fires')

In [ ]:
amz['num_of_fires'].dtype

dtype('O')

In [ ]:
#var['var_name']=var['col_name'].astype(dest_type) this is use to change the datatype of the column
amz['num_of_fires']=amz['num_of_fires'].astype(float)
amz['num_of_fires'].dtype

dtype('float64')

In [ ]:
#handling missing values("nan" values)
# 1) deleting the rows or columns which contains null values
#syntax:-
# var.dropna(inplae=True)  #it will delete the rows which contains null values
import numpy as np
s={'Sname':['yash','rahul','harsh','sumit','sumeet'],
   'Sid':[101,102,103,104,np.nan],
   'Course':['BCA','Btech','MCA','BBA',np.nan]}
sf=pd.DataFrame(s)
sf

    Sname    Sid Course
0    yash  101.0    BCA
1   rahul  102.0  Btech
2   harsh  103.0    MCA
3   sumit  104.0    BBA
4  sumeet    NaN    NaN

In [ ]:
d={'Ename':['Yash',np.nan,'Harsh','Siddhant','Sumeet'],
   'Eid':[101,102,103,104,np.nan],
   'Salary':['8LPA','5.6LPA','3LPA','7LPA','10LPA']}
df=pd.DataFrame(d)

df.dropna()
df.isnull()

   Ename    Eid  Salary
0  False  False   False
1   True  False   False
2  False  False   False
3  False  False   False
4  False   True   False

In [ ]:
wq['fixed acidity'].isnull().sum()

np.int64(0)

In [ ]:
wq.dropna(inplace=True)  #wine=wq.dropna()
wq.shape

(6463, 13)

In [ ]:
wq.isnull().sum()

type                    0
fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [ ]:
amz.shape

(6454, 5)

In [ ]:
amz.dropna(inplace=True)


amz.shape

(6322, 5)

In [ ]:
#Filling Nan values:
#1) fillna()
#2) ffill()/forward filling
#3) bFill()/backward filling

#1) fillna() :- it will fill the "Nan"  values with specified value

#syntax var['col_name']=var['col_name'].fillna('value')

#2) ffill() :- it will fill the "Nan" values with previous value of the column
#  syntax var['col_name']=var['col_name'].ffill()
#3) bfill() :- it will fill the "Nan" values with next value of the column
# syntax  var['col_name']=var['col_name'].bfill()

from textwrap import fill


s={'Sname':['yash',np.nan,'harsh','sumit','sumeet'],
   'Sid':[101,102,103,104,np.nan],
   'Course':['BCA','Btech','MCA','BBA',np.nan]}
sf=pd.DataFrame(s)
sf
sf['Sname']=sf['Sname'].fillna('Unkonwn')
sf['Course']=sf['Course'].fillna('unkown')
avg=sf['Sid'].mean()
sf['Sid']=sf['Sid'].fillna(avg)
sf

     Sname    Sid  Course
0     yash  101.0     BCA
1  Unkonwn  102.0   Btech
2    harsh  103.0     MCA
3    sumit  104.0     BBA
4   sumeet  102.6  unkown

In [ ]:
s={'Sname':['yash',np.nan,'harsh','sumit','sumeet'],
   'Sid':[101,102,103,104,np.nan],
   'Course':['BCA','Btech','MCA','BBA',np.nan]}
sf=pd.DataFrame(s)
sf

sf['Sname']=sf['Sname'].ffill()
sf

    Sname    Sid Course
0    yash  101.0    BCA
1    yash  102.0  Btech
2   harsh  103.0    MCA
3   sumit  104.0    BBA
4  sumeet    NaN    NaN

In [ ]:
s={'Sname':['yash',np.nan,'harsh','sumit','sumeet'],
   'Sid':[101,102,103,104,np.nan],
   'Course':['BCA','Btech','MCA','BBA',np.nan]}
sf=pd.DataFrame(s)
sf

sf['Sname']=sf['Sname'].bfill()
sf

    Sname    Sid Course
0    yash  101.0    BCA
1   harsh  102.0  Btech
2   harsh  103.0    MCA
3   sumit  104.0    BBA
4  sumeet    NaN    NaN

In [ ]:
#Rearranging the order of columns in the dataframe
#syntax :-
#     new_order=['col_index','col_index2'...]
#   var=var[var.columns[new_order]]

new_order=[1,0,2]
sf=sf[sf.columns[new_order]]
sf

sf[sf.columns[new_order]]

     Sid   Sname Course
0  101.0    yash    BCA
1  102.0   harsh  Btech
2  103.0   harsh    MCA
3  104.0   sumit    BBA
4    NaN  sumeet    NaN

In [ ]:
tips.columns

Index(['Unnamed: 0', 'total_bill', 'tip', 'sex', 'smoker', 'day', 'time',
       'size'],
      dtype='object')

In [ ]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [ ]:
new_order=[5,0,1,2,3,4,6]
tips[tips.columns[new_order]]

      day  Unnamed: 0  total_bill   tip     sex smoker    time
0     Sun           0       16.99  1.01  Female     No  Dinner
1     Sun           1       10.34  1.66    Male     No  Dinner
2     Sun           2       21.01  3.50    Male     No  Dinner
3     Sun           3       23.68  3.31    Male     No  Dinner
4     Sun           4       24.59  3.61  Female     No  Dinner
..    ...         ...         ...   ...     ...    ...     ...
239   Sat         239       29.03  5.92    Male     No  Dinner
240   Sat         240       27.18  2.00  Female    Yes  Dinner
241   Sat         241       22.67  2.00    Male    Yes  Dinner
242   Sat         242       17.82  1.75    Male     No  Dinner
243  Thur         243       18.78  3.00  Female     No  Dinner

[244 rows x 7 columns]

In [ ]:
hr.columns

Index(['employee_id', 'number_project', 'average_montly_hours',
       'time_spend_company', 'Work_accident', 'left', 'promotion_last_5years',
       'department', 'salary'],
      dtype='object')

In [ ]:
new=[0,8,1,3,2,6,4,5,7,]
hr[hr.columns[new]]

,employee_id,salary,number_project,time_spend_company,average_montly_hours,promotion_last_5years,Work_accident,left,department
0,1003,low,2,3,157,0,0,1,sales
1,1005,medium,5,6,262,0,0,1,sales
2,1486,medium,7,4,272,0,0,1,sales
3,1038,low,5,5,223,0,0,1,sales
4,1057,low,2,3,159,0,0,1,sales
...,...,...,...,...,...,...,...,...,...
14994,87670,low,2,3,151,0,0,1,support
14995,87673,low,2,3,160,0,0,1,support
14996,87679,low,2,3,143,0,0,1,support
14997,87681,low,6,4,280,0,0,1,support
14998,87684,low,2,3,158,0,0,1,support

In [ ]:
#resetting the index of the dataframe
#It will reset the index of the dataframe and old index will become the column

#syntax
# var.reset_index(inplace=True)

tips.reset_index(inplace=True)

tips.head()

,level_0,index,Unnamed: 0,total_bill,tip,sex,smoker,day,time,size
0,0,0,0,16.99,1.01,Female,No,Sun,Dinner,2
1,1,1,1,10.34,1.66,Male,No,Sun,Dinner,3
2,2,2,2,21.01,3.50,Male,No,Sun,Dinner,3
3,3,3,3,23.68,3.31,Male,No,Sun,Dinner,2
4,4,4,4,24.59,3.61,Female,No,Sun,Dinner,4

In [ ]:
#droping unwanted columns.
#syntax
# var.drop('col_name',axis=1) --> for single column
# var.drop(['col_name','col_name'...],axis=1)  for multiple columns

In [ ]:

s={'Sname':['yash',np.nan,'harsh','sumit','sumeet'],
   'Sid':[101,102,103,104,np.nan],
   'Course':['BCA','Btech','MCA','BBA',np.nan]}
sf

    Sname    Sid Course
0    yash  101.0    BCA
1   harsh  102.0  Btech
2   harsh  103.0    MCA
3   sumit  104.0    BBA
4  sumeet    NaN    NaN

In [ ]:
sf.drop('Sid',axis=1)

    Sname Course
0    yash    BCA
1   harsh  Btech
2   harsh    MCA
3   sumit    BBA
4  sumeet    NaN

In [ ]:
sf.drop(['Sname','Course'],axis=1)

TypeError: DataFrame.drop() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given

In [ ]:
#dropping unwanted rows
#syntax
# var.drop('row_index') --> for single column
# var.drop(['row_index1','row_index2'...])  for multiple columns
sf.drop(1)
sf.drop([2,4])

   Sname    Sid Course
0   yash  101.0    BCA
1  harsh  102.0  Btech
3  sumit  104.0    BBA

In [ ]:
# axis=1 --> column
# axis=0 --> row    by default axis=0

tips.drop('Unnamed: 0',axis=1,inplace=True)
tips.head()

KeyError: "['Unnamed: 0'] not found in axis"

In [ ]:
#set_index():
#it will set the specified column as index of dataframe
#syntax:
# var.set_index('col_name',inplace=True)

sf.set_index('Sid',inplace=True)

KeyError: "None of ['Sid'] are in the columns"

In [ ]:
sf.head()

        Sname Course
Sid
101.0    yash    BCA
102.0   harsh  Btech
103.0   harsh    MCA
104.0   sumit    BBA
NaN    sumeet    NaN

In [ ]:
sf.loc[[102,101,103],'Sname']

Sid
102.0    harsh
101.0     yash
103.0    harsh
Name: Sname, dtype: object

In [ ]:
amz.set_index('ano',inplace=True)

In [ ]:
amz.head()

          mes estado   numero  encontro
ano
1998  Janeiro   Acre  0 Fires  1/1/1998
1999  Janeiro   Acre  0 Fires  1/1/1999
2000  Janeiro   Acre  0 Fires  1/1/2000
2001  Janeiro   Acre  0 Fires  1/1/2001
2002  Janeiro   Acre  0 Fires  1/1/2002

In [ ]:
amz.loc[2000]

            mes     estado    numero  encontro
ano
2000    Janeiro       Acre   0 Fires  1/1/2000
2000  Fevereiro       Acre   0 Fires  1/1/2000
2000      Março       Acre  11 Fires  1/1/2000
2000      Abril       Acre   1 Fires  1/1/2000
2000       Maio       Acre   1 Fires  1/1/2000
...         ...        ...       ...       ...
2000     Agosto  Tocantins     1.949  1/1/2000
2000   Setembro  Tocantins     2.552  1/1/2000
2000    Outubro  Tocantins     1.053  1/1/2000
2000   Novembro  Tocantins        96  1/1/2000
2000   Dezembro  Tocantins        20  1/1/2000

[324 rows x 4 columns]

In [ ]:
amz.reset_index(inplace=True)

In [ ]:
amz.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [ ]:
ua=pd.read_csv("https://github.com/Taj1920/Data-Analysis-Datasets/raw/refs/heads/main/Datasets-Cleaning/uncleaned_appliances.csv")

In [ ]:
ua=pd.read_csv("ua.csv")
ua

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN
...,...,...,...,...,...,...,...,...
3981,NaN,NaN,NaN,NaN,$54.34,NaN,NaN,Unbeatablesale 142Mhz .25 Wave Kulduckie
3982,NaN,NaN,NaN,NaN,$64.06,NaN,NaN,Unbeatablesale 440-460Mhz Load And Tip Only -B...
3983,NaN,NaN,NaN,NaN,$61.99,-24%,NaN,"TaoTronics Air Fryer, 1700W 14.8 QT, 9 In 1 Ai..."
3984,NaN,NaN,NaN,NaN,$81.47,-3%,NaN,"Air Fryer 5.3 Quart, Digital Oilless Frying Co..."
3985,NaN,NaN,NaN,NaN,$501.21,-28%,NaN,Up To 350lbs Okin Motor Power Lift Recliner Ch...

In [ ]:
ua.head()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
0,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN,NaN
1,1pc Portable Hanging Neck Fan,https://us.shein.com/1pc-Portable-Hanging-Neck...,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN,NaN
2,1pc Pink Colored Curved Eyelash Curler False E...,https://us.shein.com/1pc-Pink-Colored-Curved-E...,NaN,NaN,$1.80,NaN,400+ sold recently,NaN
3,1 Mini Portable Handheld Fan With 2 Aa Batteri...,https://us.shein.com/1-Mini-Portable-Handheld-...,NaN,NaN,$0.88,-72%,5.6k+ sold recently,NaN
4,"Wit Water Flosser,Portable Oral Irrigator With...",https://us.shein.com/Wit-Water-Flosser-Portabl...,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN,NaN

In [ ]:
ua.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3777 entries, 0 to 3985
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   goods-title-link--jump       40 non-null     object
 1   goods-title-link--jump href  40 non-null     object
 2   rank-title                   559 non-null    object
 3   rank-sub                     559 non-null    object
 4   price                        3777 non-null   object
 5   discount                     2259 non-null   object
 6   selling_proposition          1352 non-null   object
 7   goods-title-link             3737 non-null   object
dtypes: object(8)
memory usage: 265.6+ KB

In [ ]:
ua.describe()

,goods-title-link--jump,goods-title-link--jump href,rank-title,rank-sub,price,discount,selling_proposition,goods-title-link
count,40,40,559,559,3986,2459,1361,3946
unique,40,40,10,124,1512,80,64,3590
top,1pc Rechargeable Deep Tissue Muscle Handheld M...,https://us.shein.com/1pc-Rechargeable-Deep-Tis...,#4 Best Sellers,in Hair Dryers,$2.90,-28%,10+ sold recently,Stay Cool On-The-Go: 1pc Portable USB Mini Fan
freq,1,1,63,14,35,272,221,8

In [ ]:
ua.columns

Index(['goods-title-link--jump', 'goods-title-link--jump href', 'rank-title',
       'rank-sub', 'price', 'discount', 'selling_proposition',
       'goods-title-link'],
      dtype='object')

In [ ]:
ua.shape

(3986, 8)

In [ ]:
ua.duplicated().sum()

np.int64(209)

In [ ]:
ua.isnull().sum()

goods-title-link--jump         3737
goods-title-link--jump href    3737
rank-title                     3218
rank-sub                       3218
price                             0
discount                       1518
selling_proposition            2425
goods-title-link                 40
dtype: int64

In [ ]:
ua.drop_duplicates(inplace=True)

In [ ]:
ua.shape

(3777, 8)

In [ ]:
ua['goods-title-link'].unique()

array([nan,
       '4pcs Makeup Sponge Beauty Egg Set - Makeup Sponge For Foundation Blending With Egg Holder, Perfectly Used For Cream, Powder, Blush, Concealer, And Liquid',
       '1pc Salon Tools Black Pink Universal Silicone Hair Dryer Diffuser Hood Adjustable Temperature Dispersion Resistant Drying Hair Dryer',
       ...,
       'TaoTronics Air Fryer, 1700W 14.8 QT, 9 In 1 Air Fryer Oven, Oil-Less Cooker With Rotisserie Shaft AF010',
       'Air Fryer 5.3 Quart, Digital Oilless Frying Cooker, Auto Shut Off, Stainless Steel, 8 Preset Programs, 1700W',
       'Up To 350lbs Okin Motor Power Lift Recliner Chair For Elderly, Heavy Duty Motion Mechanism With 8-Point Vibration Massage And Lumbar Heating, Two Cup Holders And USB Charge Port, Brown'],
      shape=(3591,), dtype=object)

In [ ]:
ua.drop(['goods-title-link--jump','goods-title-link--jump href','goods-title-link'],axis=1,inplace=True)#removing columns

In [ ]:
ua.head()

,rank-title,rank-sub,price,discount,selling_proposition
0,#1 Best Sellers,in Give Gifts,$2.03,-22%,NaN
1,#4 Best Sellers,in Top rated in Portable Fans,$6.48,-20%,NaN
2,NaN,NaN,$1.80,NaN,400+ sold recently
3,NaN,NaN,$0.88,-72%,5.6k+ sold recently
4,#6 Best Sellers,in Oral Irrigators,$12.06,-40%,NaN

In [ ]:
ua['rank-title'].unique()  #checking unique column of rank title

array(['#1 Best Sellers', '#4 Best Sellers', nan, '#6 Best Sellers',
       '#10 Best Sellers', '#8 Best Sellers', '#9 Best Sellers',
       '#5 Best Sellers', '#2 Best Sellers', '#7 Best Sellers',
       '#3 Best Sellers'], dtype=object)

In [ ]:
#removing unwanted data 
ua['rank-title']=ua['rank-title'].str.strip('# Best Sellers')

#Converting data into integer

ua['rank-title']=ua['rank-title'].astype('Int64')

In [ ]:
avg=round(ua['rank-title'].mean())
ua['rank-title']=ua['rank-title'].fillna(avg)

In [ ]:
ua['rank-title'].unique()

<IntegerArray>
[1, 4, 5, 6, 10, 8, 9, 2, 7, 3]
Length: 10, dtype: Int64

In [3]:
import pandas as pd
import numpy as np
tips=pd.read_csv("tips.csv")

In [4]:
wq=pd.read_csv("winequality.csv")

In [5]:
hr=pd.read_csv("hr.csv")

In [6]:
amz=pd.read_csv("amzz.csv",encoding='ISO-8859-1')

In [7]:
ti=pd.read_csv("titanic.csv")

In [ ]:
ua.head()

,rank-title,rank-sub,price,discount,selling_proposition
0,1,in Give Gifts,$2.03,-22%,NaN
1,4,in Top rated in Portable Fans,$6.48,-20%,NaN
2,5,NaN,$1.80,NaN,400+ sold recently
3,5,NaN,$0.88,-72%,5.6k+ sold recently
4,6,in Oral Irrigators,$12.06,-40%,NaN

In [ ]:
ua['rank-sub'].unique()

array([' Give Gifts', ' Top rated in Portable Fans', nan,
       ' Oral Irrigators', ' Refrigerators & Freezers',
       ' Other Household Appliances', ' Oral Care Appliances',
       ' Household Appliances', ' Women Shave & Hair Removal Appliances',
       ' Vacuum Food Sealers', ' Juicer & Food Processor',
       ' Cleaning Appliance Parts', ' Laundry Appliances',
       ' Fruit & Vegetable Tools', ' Blenders', ' Kitchen Meat Grinders',
       ' Egg Cookers', ' Air Purifiers', ' Other Body Care Machines',
       ' Hair Dryers', ' Electric Nose & Ear Trimmers',
       ' Electric Toothbrushes', ' Specialty Kitchen Appliances',
       ' Led Makeup Mirror', ' Heater & Cooler', ' Electric Space Heater',
       ' Juicer Machines', ' Men Shave & Hair Removal Appliances',
       ' Personal Size Blenders', ' Kitchen Appliance Parts',
       ' Personal Care Appliance Accessories', ' Car Vacuum Cleaner',
       ' Power Toothbrushes', ' Curling Tongs & Curling Wands',
       ' Water Treatment Appliances', ' Hair Styling Care Appliances',
       ' Cleaning Appliances', ' Electric Hair Clippers',
       ' Environmental Appliances', ' Kitchen Appliances',
       ' Hand Blenders', ' Milk Frothers', ' Other Styling Tools',
       ' Other Kitchen Appliances', ' Humidifier',
       ' Major Appliances Parts', ' Wax Heaters',
       ' Massage & Relaxation Tools',
       ' Electric Grills & Electric Griddles', ' Portable Refrigerator',
       ' Epilators', ' Electronic Foot Files', ' Coffee & Tea Appliances',
       ' Oximeter & Blood Pressure Meter', ' Digital Kitchen Scales',
       ' Measuring Tools', ' Hair Straightening Irons',
       ' Digital Thermometers & Timers', ' Cooking Appliances',
       ' Electric Blade Grinders', ' Electric Salt & Pepper Grinders',
       ' Waffle Makers', ' Kitchen Timers', ' Personal Care Appliances',
       ' Ultrasonic Cleaners', ' Refrigerators',
       ' Women Electric Shavers', ' Food Processors', ' Garment Steamers',
       ' Electronic Beauty Instruments', ' Electric Lunch Boxes',
       ' Electric Kettles', ' Personal Care Appliance', ' Table Fans',
       ' Air Fryers', ' Health & Wellness Monitors',
       ' Ice Crushers & Shavers', ' Handle Fans',
       ' Massage Tools & Equipment', ' Temperature Gauges',
       ' Electronic Nail Art Equipment', ' Aroma Diffuser',
       ' Water and Ice Dispensers', ' Electric Hair Brushes',
       ' Rice Cookers', ' Electric Eyebrow Trimmer', ' Egg Tools',
       ' Aromatherapy', ' Summer Travel Bestsellers',
       ' Styling Tools & Appliances', ' Car Electronics',
       ' Hot Tea Makers', ' Meat & Poultry Tools',
       ' Electric Cleaning Brushes', ' Dehumidifiers', ' Lint Removers',
       ' Beauty & Body Care Appliances', ' Hair Clippers',
       ' Exhaust Fans', ' Home Appliances', ' Portable Fans',
       ' Slow Cookers', ' Kitchen Scales', ' Hair Curling Irons',
       ' Portable Vacuums', ' Popcorn Makers', ' Electric Deep Fryers',
       ' Laser Hair Removal Devices', ' Vacuum Cleaners', ' Ice Makers',
       ' Other Coffee Makers', ' Air Conditioners', ' Washers & Dryers',
       ' Stick Vacuum Cleaners', ' Electric Shavers',
       ' Portable Washing Machines', ' Water Filter Cartridges',
       ' Meat Grinders', ' Electric Blankets', ' Washing Machines',
       ' Stand Mixers', ' Major Appliances', ' Massage Chair',
       ' Warming Products', ' Hot Plates'], dtype=object)

In [ ]:
ua['rank-sub']=ua['rank-sub'].str.strip('in')

In [ ]:
ua['rank-sub'].isnull().sum()

KeyError: 'rank-sub'

In [ ]:
ua.drop('rank-sub',axis=1,inplace=True)

In [ ]:
ua.head()

   rank-title   price discount  selling_proposition
0           1   $2.03     -22%                  NaN
1           4   $6.48     -20%                  NaN
2           5   $1.80      NaN   400+ sold recently
3           5   $0.88     -72%  5.6k+ sold recently
4           6  $12.06     -40%                  NaN

In [ ]:
ua['price'].unique()

array(['2.03', '6.48', '1.80', ..., '60.47', '1,499.99', '54.34'],
      shape=(1512,), dtype=object)

In [ ]:
ua['price']=ua['price'].str.strip('$')

In [ ]:
ua['price']=ua['price']

In [ ]:
ua['price'].unique()

array(['2.03', '6.48', '1.80', ..., '60.47', '1,499.99', '54.34'],
      shape=(1512,), dtype=object)

In [ ]:
ua.head()

   rank-title  price discount  selling_proposition
0           1   2.03     -22%                  NaN
1           4   6.48     -20%                  NaN
2           5   1.80      NaN   400+ sold recently
3           5   0.88     -72%  5.6k+ sold recently
4           6  12.06     -40%                  NaN

In [ ]:

ua['price']=ua['price'].astype(float)

In [ ]:
ua['price']=ua['price'].str.replace(',','')

In [ ]:
ua['price']=ua['price']*95
ua['price'].unique()

array([   192.85,    615.6 ,    171.  , ...,   5744.65, 142499.05,
         5162.3 ], shape=(1512,))

In [ ]:
out=[]
for i in ua['price']:
    out.append(i*95)
ua['price']=out

In [ ]:
out=[]
for i in ua['price']:
    out.append('₹'+str(i))  #str() is used to convert the float value into string
ua['price']=out

In [ ]:
ua.head()

   rank-title    price discount  selling_proposition
0           1  ₹192.85     -22%                  NaN
1           4   ₹615.6     -20%                  NaN
2           5   ₹171.0      NaN   400+ sold recently
3           5    ₹83.6     -72%  5.6k+ sold recently
4           6  ₹1145.7     -40%                  NaN

In [ ]:
#group by

#When we want to group the data based on some column and want to perform some operation on that column we use groupby() function
#we split the data into groups and then we perform some operation on that group and then we combine the result of that operation to get the final result
#syntax: 

#  var_1=var.groupby('categorical_column')
# var_1.groups  --> to dislpay the groups of that particular column
# var_1.get_group('group_name')  #it will return the group of that particular group name

In [ ]:
gr_wq=wq.groupby('type')

In [ ]:
gr_wq.groups

{'red': [4898, 4899, 4900, 4901, 4902, 4903, 4904, 4905, 4906, 4907, 4908, 4909, 4910, 4911, 4912, 4913, 4914, 4915, 4916, 4917, 4918, 4919, 4920, 4921, 4922, 4923, 4924, 4925, 4926, 4927, 4928, 4929, 4930, 4931, 4932, 4933, 4934, 4935, 4936, 4937, 4938, 4939, 4940, 4941, 4942, 4943, 4944, 4945, 4946, 4947, 4948, 4949, 4950, 4951, 4952, 4953, 4954, 4955, 4956, 4957, 4958, 4959, 4960, 4961, 4962, 4963, 4964, 4965, 4966, 4967, 4968, 4969, 4970, 4971, 4972, 4973, 4974, 4975, 4976, 4977, 4978, 4979, 4980, 4981, 4982, 4983, 4984, 4985, 4986, 4987, 4988, 4989, 4990, 4991, 4992, 4993, 4994, 4995, 4996, 4997, ...], 'white': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]}

In [ ]:
white_w=gr_wq.get_group('white')

In [ ]:
white_w.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [ ]:
hr.head(
    
)

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [ ]:

gr_dept=hr.groupby('department')

In [ ]:
gr_dept.groups

{'IT': [61, 62, 63, 64, 65, 70, 138, 139, 140, 141, 142, 147, 214, 215, 216, 217, 218, 223, 291, 292, 293, 294, 295, 300, 367, 368, 369, 370, 371, 376, 443, 444, 445, 446, 447, 452, 519, 520, 521, 522, 523, 528, 595, 596, 597, 598, 599, 604, 671, 672, 673, 674, 675, 680, 747, 748, 749, 750, 751, 756, 823, 824, 825, 826, 827, 832, 899, 900, 901, 902, 903, 908, 975, 976, 977, 978, 979, 984, 1051, 1052, 1053, 1054, 1055, 1060, 1127, 1128, 1129, 1130, 1131, 1136, 1204, 1205, 1206, 1207, 1208, 1213, 1214, 1215, 1216, 1281, ...], 'RandD': [301, 302, 303, 304, 305, 453, 454, 455, 456, 457, 605, 606, 607, 608, 609, 833, 834, 835, 836, 837, 985, 986, 987, 988, 989, 1061, 1062, 1063, 1064, 1065, 1217, 1218, 1219, 1291, 1292, 1293, 1294, 1295, 1296, 1368, 1369, 1370, 1371, 1372, 1373, 1445, 1446, 1447, 1448, 1449, 1450, 1522, 1523, 1524, 1525, 1526, 1598, 1599, 1600, 1601, 1602, 1675, 1676, 1677, 1678, 1679, 1751, 1752, 1753, 1754, 1755, 1827, 1828, 1829, 1830, 1831, 1903, 1904, 1905, 1906, 1907, 1979, 1980, 1981, 1982, 1983, 2055, 2056, 2057, 2058, 2059, 2131, 2132, 2133, 2134, 2135, 2207, 2208, 2209, 2210, ...], 'accounting': [28, 29, 30, 79, 105, 106, 107, 155, 181, 182, 183, 224, 225, 232, 258, 259, 260, 308, 334, 335, 336, 377, 378, 384, 410, 411, 412, 460, 486, 487, 488, 529, 530, 536, 562, 563, 564, 612, 638, 639, 640, 688, 714, 715, 716, 764, 790, 791, 792, 840, 866, 867, 868, 916, 942, 943, 944, 992, 1018, 1019, 1020, 1068, 1094, 1095, 1096, 1145, 1171, 1172, 1173, 1222, 1248, 1249, 1250, 1299, 1325, 1326, 1327, 1376, 1402, 1403, 1404, 1453, 1479, 1480, 1481, 1529, 1555, 1556, 1557, 1606, 1632, 1633, 1634, 1682, 1708, 1709, 1710, 1758, 1784, 1785, ...], 'hr': [31, 32, 33, 34, 108, 109, 110, 111, 184, 185, 186, 187, 226, 227, 228, 261, 262, 263, 264, 337, 338, 339, 340, 379, 380, 381, 413, 414, 415, 416, 489, 490, 491, 492, 531, 532, 533, 565, 566, 567, 568, 641, 642, 643, 644, 717, 718, 719, 720, 793, 794, 795, 796, 869, 870, 871, 872, 945, 946, 947, 948, 1021, 1022, 1023, 1024, 1097, 1098, 1099, 1100, 1174, 1175, 1176, 1177, 1251, 1252, 1253, 1254, 1328, 1329, 1330, 1331, 1405, 1406, 1407, 1408, 1482, 1483, 1484, 1485, 1558, 1559, 1560, 1561, 1635, 1636, 1637, 1638, 1711, 1712, 1713, ...], 'management': [60, 82, 137, 158, 213, 235, 290, 311, 366, 387, 442, 463, 518, 539, 594, 615, 670, 691, 746, 767, 822, 843, 898, 919, 974, 995, 1050, 1071, 1126, 1148, 1203, 1225, 1280, 1302, 1357, 1379, 1434, 1456, 1511, 1532, 1587, 1609, 1664, 1685, 1740, 1761, 1816, 1837, 1892, 1913, 1968, 1989, 2044, 2065, 2120, 2141, 2196, 2217, 2272, 2293, 2348, 2369, 2424, 2445, 2500, 2522, 2577, 2599, 2654, 2676, 2731, 2753, 2808, 2830, 2885, 2906, 2961, 2983, 3038, 3059, 3114, 3135, 3190, 3211, 3266, 3287, 3342, 3363, 3418, 3439, 3494, 3515, 3570, 3591, 3646, 3667, 3722, 3743, 3798, 3819, ...], 'marketing': [77, 83, 84, 85, 148, 149, 150, 151, 152, 153, 159, 160, 161, 229, 230, 236, 237, 238, 306, 312, 313, 314, 382, 388, 389, 390, 458, 464, 465, 466, 534, 540, 541, 542, 610, 616, 617, 618, 686, 692, 693, 694, 762, 768, 769, 770, 838, 844, 845, 846, 914, 920, 921, 922, 990, 996, 997, 998, 1066, 1072, 1073, 1074, 1142, 1143, 1149, 1150, 1151, 1220, 1226, 1227, 1228, 1297, 1303, 1304, 1305, 1374, 1380, 1381, 1382, 1451, 1457, 1458, 1459, 1527, 1533, 1534, 1535, 1603, 1604, 1610, 1611, 1612, 1680, 1686, 1687, 1688, 1756, 1762, 1763, 1764, ...], 'product_mng': [66, 67, 68, 69, 71, 72, 73, 74, 75, 76, 143, 144, 145, 146, 219, 220, 221, 222, 296, 297, 298, 299, 372, 373, 374, 375, 448, 449, 450, 451, 524, 525, 526, 527, 600, 601, 602, 603, 676, 677, 678, 679, 752, 753, 754, 755, 828, 829, 830, 831, 904, 905, 906, 907, 980, 981, 982, 983, 1056, 1057, 1058, 1059, 1132, 1133, 1134, 1135, 1209, 1210, 1211, 1212, 1286, 1287, 1288, 1289, 1363, 1364, 1365, 1366, 1440, 1441, 1442, 1443, 1517, 1518, 1519, 1520, 1593, 1594, 1595, 1596, 1670, 1671, 1672, 1673, 1746, 1747, 1748, 1749, 1822, 1823, ...], 'sales': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 78, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 154, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 231, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 307, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, ...], 'support': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 80, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 156, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 233, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 309, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 385, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 461, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 537, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 613, 656, 657, 658, 659, ...], 'technical': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 57, 58, 59, 81, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 134, 135, 136, 157, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 210, 211, 212, 234, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 287, 288, 289, 310, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 363, 364, 365, 386, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 439, 440, 441, 462, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, ...]}

In [ ]:
IT_dept=gr_dept.get_group('IT')

In [ ]:
hr['department'].unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [ ]:
sales_dept=gr_dept.get_group('sales')

In [ ]:
sales_dept['employee_id'].count()

np.int64(4140)

In [ ]:
gr_dept.get_group('sales')['employee_id'].count()

np.int64(4140)

In [ ]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [ ]:
gr_dept.get_group('IT')['left'].sum()

np.int64(273)

In [ ]:
gr_dept.get_group('RandD')['number_project'].mean()

np.float64(3.8538754764930117)

In [ ]:
gr_dept.get_group('hr')['employee_id'].count()

np.int64(739)

In [ ]:
#group by for 3 columns
#syntax
#var_1=var.groupby(['categorical_col1','ategorical_col2'])
#var_1.groups
#var_1.get_group(('group_1','group_2'))

In [ ]:
gender=tips.groupby('sex')

males=gender.get_group('Male')

ge_smokers=tips.groupby(['sex','smoker'])

In [ ]:
ge_smokers.groups

{('Female', 'No'): [0, 4, 11, 14, 16, 18, 21, 22, 29, 32, 33, 37, 51, 52, 57, 66, 71, 74, 82, 85, 94, 104, 111, 114, 115, 117, 118, 119, 121, 124, 125, 127, 128, 131, 132, 133, 134, 135, 136, 137, 139, 140, 143, 144, 145, 146, 147, 155, 157, 158, 162, 223, 238, 243], ('Female', 'Yes'): [67, 72, 73, 92, 93, 100, 101, 102, 103, 109, 164, 168, 169, 178, 186, 188, 191, 197, 198, 201, 202, 203, 205, 209, 213, 214, 215, 219, 221, 225, 226, 229, 240], ('Male', 'No'): [1, 2, 3, 5, 6, 7, 8, 9, 10, 12, 13, 15, 17, 19, 20, 23, 24, 25, 26, 27, 28, 30, 31, 34, 35, 36, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 53, 54, 55, 59, 64, 65, 68, 70, 75, 77, 78, 79, 81, 84, 86, 87, 88, 89, 91, 99, 108, 110, 112, 113, 116, 120, 122, 123, 126, 129, 130, 141, 142, 148, 149, 150, 151, 152, 153, 154, 156, 159, 160, 161, 163, 165, 166, 167, 185, 195, 212, 227, 228, 232, 233, 235, 239, 242], ('Male', 'Yes'): [56, 58, 60, 61, 62, 63, 69, 76, 80, 83, 90, 95, 96, 97, 98, 105, 106, 107, 138, 170, 171, 172, 173, 174, 175, 176, 177, 179, 180, 181, 182, 183, 184, 187, 189, 190, 192, 193, 194, 196, 199, 200, 204, 206, 207, 208, 210, 211, 216, 217, 218, 220, 222, 224, 230, 231, 234, 236, 237, 241]}

In [ ]:
female_smokers=ge_smokers.get_group(('Female','Yes'))

In [ ]:
female_smokers

     Unnamed: 0  total_bill   tip     sex smoker   day    time  size
67           67        3.07  1.00  Female    Yes   Sat  Dinner     1
72           72       26.86  3.14  Female    Yes   Sat  Dinner     2
73           73       25.28  5.00  Female    Yes   Sat  Dinner     2
92           92        5.75  1.00  Female    Yes   Fri  Dinner     2
93           93       16.32  4.30  Female    Yes   Fri  Dinner     2
100         100       11.35  2.50  Female    Yes   Fri  Dinner     2
101         101       15.38  3.00  Female    Yes   Fri  Dinner     2
102         102       44.30  2.50  Female    Yes   Sat  Dinner     3
103         103       22.42  3.48  Female    Yes   Sat  Dinner     2
109         109       14.31  4.00  Female    Yes   Sat  Dinner     2
164         164       17.51  3.00  Female    Yes   Sun  Dinner     2
168         168       10.59  1.61  Female    Yes   Sat  Dinner     2
169         169       10.63  2.00  Female    Yes   Sat  Dinner     2
178         178        9.60  4.00  Female    Yes   Sun  Dinner     2
186         186       20.90  3.50  Female    Yes   Sun  Dinner     3
188         188       18.15  3.50  Female    Yes   Sun  Dinner     3
191         191       19.81  4.19  Female    Yes  Thur   Lunch     2
197         197       43.11  5.00  Female    Yes  Thur   Lunch     4
198         198       13.00  2.00  Female    Yes  Thur   Lunch     2
201         201       12.74  2.01  Female    Yes  Thur   Lunch     2
202         202       13.00  2.00  Female    Yes  Thur   Lunch     2
203         203       16.40  2.50  Female    Yes  Thur   Lunch     2
205         205       16.47  3.23  Female    Yes  Thur   Lunch     3
209         209       12.76  2.23  Female    Yes   Sat  Dinner     2
213         213       13.27  2.50  Female    Yes   Sat  Dinner     2
214         214       28.17  6.50  Female    Yes   Sat  Dinner     3
215         215       12.90  1.10  Female    Yes   Sat  Dinner     2
219         219       30.14  3.09  Female    Yes   Sat  Dinner     4
221         221       13.42  3.48  Female    Yes   Fri   Lunch     2
225         225       16.27  2.50  Female    Yes   Fri   Lunch     2
226         226       10.09  2.00  Female    Yes   Fri   Lunch     2
229         229       22.12  2.88  Female    Yes   Sat  Dinner     2
240         240       27.18  2.00  Female    Yes   Sat  Dinner     2

In [ ]:
ge_smokers.get_group(('Female','No')).count()

Unnamed: 0    54
total_bill    54
tip           54
sex           54
smoker        54
day           54
time          54
size          54
dtype: int64

In [ ]:
M_S=ge_smokers.get_group(('Male','Yes')).count()

Unnamed: 0    60
total_bill    60
tip           60
sex           60
smoker        60
day           60
time          60
size          60
dtype: int64

In [ ]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [ ]:
dep_sal=hr.groupby(['department','salary'])

In [60]:
dep_sal.get_group(('IT','high'))['employee_id'].count()

np.int64(83)

In [61]:
dep_sal.get_group(('sales','low'))['number_project'].mean()

np.float64(3.7579799904716533)

In [68]:
ge_smokers.get_group(('Male','No'))['tip'].mean()

np.float64(3.11340206185567)

In [62]:
tips.head()

   Unnamed: 0  total_bill   tip     sex smoker  day    time  size
0           0       16.99  1.01  Female     No  Sun  Dinner     2
1           1       10.34  1.66    Male     No  Sun  Dinner     3
2           2       21.01  3.50    Male     No  Sun  Dinner     3
3           3       23.68  3.31    Male     No  Sun  Dinner     2
4           4       24.59  3.61  Female     No  Sun  Dinner     4

In [69]:
m_dinn=tips.groupby(['sex','time'])
m_dinn.get_group(('Male','Dinner'))['sex'].count()

np.int64(124)

In [15]:

   #247.39

tips.groupby('day')['tip'].sum()

day
Fri      51.96
Sat     260.40
Sun     247.39
Thur    171.83
Name: tip, dtype: float64

In [74]:
wq.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [14]:
wq.groupby('type')['pH'].mean()

type
red      3.310864
white    3.188203
Name: pH, dtype: float64

In [83]:
ti.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [86]:
ti_fem=ti.groupby(['pclass','sex'])
ti_fem.get_group((1,'female'))['sex'].count()

np.int64(144)

In [ ]:
# Concatenation of Dataframe
#  it is a process of merging two or more dataframes
#syntax
#  1) vertical --> row by row
          # pd.concat([var1,var2...])
#  2) horizontal --> column by column
#            pd.concat([var1,var2...],axis=1)

In [93]:
s={'Sname':['yash','ali','harsh','sumit','sumeet'],
   'Sid':[101,102,103,104,105],
   'Course':['BCA','Btech','MCA','BBA','MBA']}
sf=pd.DataFrame(s)
sf

    Sname  Sid Course
0    yash  101    BCA
1     ali  102  Btech
2   harsh  103    MCA
3   sumit  104    BBA
4  sumeet  105    MBA

In [94]:
df1={'Sname':['Ritesh','Arun','Pradeep'],
                  'S_id':[105,108,109],
                  'Course':['Science','Bcom','Arts']}
df1=pd.DataFrame(df1)

d={'ename':['yash','rahul','harsh','siddhant','sumeet'],
   'Eid':[101,102,103,104,105],
   'Salary':['8LPA','5.6LPA','3LPA','7LPA','10LPA']}

df=pd.DataFrame(d)
df

      ename  Eid  Salary
0      yash  101    8LPA
1     rahul  102  5.6LPA
2     harsh  103    3LPA
3  siddhant  104    7LPA
4    sumeet  105   10LPA

In [97]:
pd.concat([df,df1])

      ename    Eid  Salary    Sname   S_id   Course
0      yash  101.0    8LPA      NaN    NaN      NaN
1     rahul  102.0  5.6LPA      NaN    NaN      NaN
2     harsh  103.0    3LPA      NaN    NaN      NaN
3  siddhant  104.0    7LPA      NaN    NaN      NaN
4    sumeet  105.0   10LPA      NaN    NaN      NaN
0       NaN    NaN     NaN   Ritesh  105.0  Science
1       NaN    NaN     NaN     Arun  108.0     Bcom
2       NaN    NaN     NaN  Pradeep  109.0     Arts

In [98]:
pd.concat([df,df1],axis=1)

      ename  Eid  Salary    Sname   S_id   Course
0      yash  101    8LPA   Ritesh  105.0  Science
1     rahul  102  5.6LPA     Arun  108.0     Bcom
2     harsh  103    3LPA  Pradeep  109.0     Arts
3  siddhant  104    7LPA      NaN    NaN      NaN
4    sumeet  105   10LPA      NaN    NaN      NaN

In [ ]:
#joins
#  when we want to fetch the data  from 2 different DataFrames simultaneously we use joins
# Types:
# 1) inner() 
# 2) outer()
# 3) left()
# 4) right()
# syntax:
# pd.merge(var1,var2,on='common_col',how='inner/outer/left/right')

In [ ]:
d={'ename':['yash','rahul','harsh','siddhant','sumeet'],
   'Eid':[101,102,103,104,105],
   'Salary':['8LPA','5.6LPA','3LPA','7LPA','10LPA']}

df=pd.DataFrame(d)
df

df11=({'Blood_Group':['A-','B+','O-','A+'],
                   'Eid':[105,104,103,106],
                   'Bonus':['12K','3K','5K','9K']})
df_1=pd.DataFrame(df11)
df_1

  Blood_Group  Eid Bonus
0          A-  105   12K
1          B+  104    3K
2          O-  103    5K
3          A+  106    9K

In [107]:
pd.merge(df,df_1,on='Eid',how='inner')

      ename  Eid Salary Blood_Group Bonus
0     harsh  103   3LPA          O-    5K
1  siddhant  104   7LPA          B+    3K
2    sumeet  105  10LPA          A-   12K

In [108]:
pd.merge(df,df_1,on='Eid',how='outer')

      ename  Eid  Salary Blood_Group Bonus
0      yash  101    8LPA         NaN   NaN
1     rahul  102  5.6LPA         NaN   NaN
2     harsh  103    3LPA          O-    5K
3  siddhant  104    7LPA          B+    3K
4    sumeet  105   10LPA          A-   12K
5       NaN  106     NaN          A+    9K

In [109]:
pd.merge(df,df_1,on='Eid',how='left')

      ename  Eid  Salary Blood_Group Bonus
0      yash  101    8LPA         NaN   NaN
1     rahul  102  5.6LPA         NaN   NaN
2     harsh  103    3LPA          O-    5K
3  siddhant  104    7LPA          B+    3K
4    sumeet  105   10LPA          A-   12K

In [110]:
pd.merge(df,df_1,on='Eid',how='right')

      ename  Eid Salary Blood_Group Bonus
0    sumeet  105  10LPA          A-   12K
1  siddhant  104   7LPA          B+    3K
2     harsh  103   3LPA          O-    5K
3       NaN  106    NaN          A+    9K

In [ ]:
#feature engineering: 

# it is the process of creating new columns based existing columns

In [10]:
ti.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0

In [8]:
ti['family_count_without_traveler']=ti['sibsp']+ti['parch']
ti['family_count_including_travel']=ti['family_count_without_traveler']+1

In [16]:
s='Allen, Miss. Elisabeth Walton'.split(',')[1].split('.')[0]

ti['family_name']=ti['name']

' Miss'

In [18]:
ti['surname']=ti['name'].str.split(',').str[0]
ti['prefix']=ti['name'].str.split(',').str[1].str.split('.').str[0]
# we split the name column with the help of ',' and then we split the second part of the name with the help of '.' and then we take the first part of that split which is the designation of the person
#or
out=[]
for i in ti['name']:
    p=i.split(',')[1].split('.')[0]
    out.append(p)
ti['prefix_1']=out
ti.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,family_count_without_traveler,family_count_including_travel,surname,designation,family_name,prefix,prefix_1
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,0,1,Allen,Miss,"Allen, Miss. Elisabeth Walton",Miss,Miss
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,3,4,Allison,Master,"Allison, Master. Hudson Trevor",Master,Master
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison,Miss,"Allison, Miss. Helen Loraine",Miss,Miss
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison,Mr,"Allison, Mr. Hudson Joshua Creighton",Mr,Mr
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison,Mrs,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",Mrs,Mrs

In [16]:
out=[]
for i in ti['name']:
    n=i.split(',')[0]
    out.append(n)
ti['family_name']=out

In [13]:
ti['designation'].unique()

array([' Miss', ' Master', ' Mr', ' Mrs', ' Col', ' Mme', ' Dr', ' Major',
       ' Capt', ' Lady', ' Sir', ' Mlle', ' Dona', ' Jonkheer',
       ' the Countess', ' Don', ' Rev', ' Ms'], dtype=object)

In [33]:
total_amount=tips.groupby(['total_bill','tip'])
total_amount=(tips['total_bill'] + tips['tip']).sum()
print(total_amount)

5559.35

In [ ]:
#pivot table
#It is called as power house of pandas
# It is used to apply multiple aggregation funcions on multiple columns at the same time
#syntax
#  var.pivot_table(values=['col1','col2',..],
#                  index='categorical_column'
#                  aggfunc=['fname_1','f_name2'..])

In [32]:
wq.pivot_table(values=['pH','quality','alcohol'],
               index='type',
               aggfunc=['mean','sum','max'])

            mean                           sum                       max  \
         alcohol        pH   quality   alcohol        pH quality alcohol
type
red    10.422983  3.310864  5.636023  16666.35   5287.45    9012    14.9
white  10.514267  3.188203  5.877909  51498.88  15593.50   28790    14.2


         pH quality
type
red    4.01       8
white  3.82       9

In [34]:
hr.head()

,employee_id,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,department,salary
0,1003,2,157,3,0,1,0,sales,low
1,1005,5,262,6,0,1,0,sales,medium
2,1486,7,272,4,0,1,0,sales,medium
3,1038,5,223,5,0,1,0,sales,low
4,1057,2,159,3,0,1,0,sales,low

In [42]:
hr.pivot_table(values=['number_project','salary','time_spend_company','average_montly_hours'],               
               index='department',
               aggfunc=['min','count','max'])

                             min                                           \
            average_montly_hours number_project salary time_spend_company
department
IT                            96              2   high                  2
RandD                         98              2   high                  2
accounting                    97              2   high                  2
hr                            98              2   high                  2
management                    97              2   high                  2
marketing                     96              2   high                  2
product_mng                   98              2   high                  2
sales                         96              2   high                  2
support                       96              2   high                  2
technical                     97              2   high                  2

                           count                                           \
            average_montly_hours number_project salary time_spend_company
department
IT                          1227           1227   1227               1227
RandD                        787            787    787                787
accounting                   767            767    767                767
hr                           739            739    739                739
management                   630            630    630                630
marketing                    858            858    858                858
product_mng                  902            902    902                902
sales                       4140           4140   4140               4140
support                     2229           2229   2229               2229
technical                   2720           2720   2720               2720

                             max
            average_montly_hours number_project  salary time_spend_company
department
IT                           308              7  medium                 10
RandD                        308              7  medium                  8
accounting                   310              7  medium                 10
hr                           310              7  medium                  8
management                   307              7  medium                 10
marketing                    310              7  medium                 10
product_mng                  310              7  medium                 10
sales                        310              7  medium                 10
support                      310              7  medium                 10
technical                    310              7  medium                 10

In [43]:
ti.head()

,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,survived,family_count_without_traveler,family_count_including_travel,surname,designation,family_name,prefix,prefix_1
0,1,"Allen, Miss. Elisabeth Walton",female,29.0000,0,0,24160,211.3375,B5,S,1,0,1,Allen,Miss,"Allen, Miss. Elisabeth Walton",Miss,Miss
1,1,"Allison, Master. Hudson Trevor",male,0.9167,1,2,113781,151.5500,C22 C26,S,1,3,4,Allison,Master,"Allison, Master. Hudson Trevor",Master,Master
2,1,"Allison, Miss. Helen Loraine",female,2.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison,Miss,"Allison, Miss. Helen Loraine",Miss,Miss
3,1,"Allison, Mr. Hudson Joshua Creighton",male,30.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison,Mr,"Allison, Mr. Hudson Joshua Creighton",Mr,Mr
4,1,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0000,1,2,113781,151.5500,C22 C26,S,0,3,4,Allison,Mrs,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",Mrs,Mrs

In [47]:
ti.pivot_table(values=['age','sibsp','fare','survived'],
                index='sex',
                aggfunc=['min','max','mean'])

           min                        max                                mean  \
           age  fare sibsp survived   age      fare sibsp survived        age
sex
female  0.1667  6.75     0        0  76.0  512.3292     8        1  28.687071
male    0.3333  0.00     0        0  80.0  512.3292     8        1  30.585233


             fare     sibsp  survived
sex
female  46.198097  0.652361  0.727468
male    26.154601  0.413998  0.190985

In [ ]:
#DateTime
#it converts the datatype of the column into datetime format
#pd.to_datetime(var['col_name'])  it is used to convert the string date into datetime format

In [53]:

amz.head()
amz['encontro']=pd.to_datetime(amz['encontro'])

In [54]:
amz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ano       6454 non-null   int64
 1   mes       6454 non-null   object
 2   estado    6454 non-null   object
 3   numero    6322 non-null   object
 4   encontro  6454 non-null   datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 252.2+ KB

In [ ]:
# date_range()
# it will create Dates between specified range
# syntax :
#         pd.date_range(start='MM/DD/YYYY',
                   #    end='MM/DD/YYYY',
                  #     freq='char' )

In [61]:
pd.date_range(start='07/01/2001',
              end='31/12/2001',
              freq='ME')

DatetimeIndex(['2001-07-31', '2001-08-31', '2001-09-30', '2001-10-31',
               '2001-11-30', '2001-12-31'],
              dtype='datetime64[ns]', freq='ME')